// 自動生成: scratchpad/gen_auto_library_data.py（元: public/se/lib/manifest.json）。手で編集しない。
// 生成 2026-09-29T13:30:04Z・出典 mixkit: Mixkit Sound Effects Free License（商用可・帰属不要・音源単体の再配布は不可）https://mixkit.co/license/#sfxFree / freesound: Creative Commons 0（CC0・帰属不要）検索フィルタで絞り込み https://freesound.org/ / maou: 魔王魂 素材利用規約（商用可・改変可・可能な限り「効果音：魔王魂」の著作表記）https://maou.audio/rule/ / nicommons: ニコニ・コモンズ（素材ごとの利用条件に従う: 利用範囲がインターネット上/制限なし・個人の配信/その他の収益化 OK・親作品登録不要。作者と素材番号は credits.nicommons）https://commons.nicovideo.jp/
export interface AutoLibraryFile {
  /** サイト相対 URL（public/se/lib/…） */
  file: string;
  /** 元のタイトル（英語・ラベル表示用） */
  title: string;
  seconds: number;
}

/** ミックスに使ったニコニ・コモンズの素材（SE タブのクレジット表示用） */
export interface AutoLibraryCredit {
  /** 素材番号（nc…） */
  id: string;
  title: string;
  /** 作者のニックネーム */
  author: string;
  /** 作者が求める・希望する表記（無ければ空） */
  notice: string;
}

export const AUTO_LIBRARY: Readonly<Record<string, readonly AutoLibraryFile[]>> = {
  "fireworks": [
    { file: "/se/lib/fireworks/v4-1.mp3", title: "fireworks ミックス 1（12 素材・うちニコニ・コモンズ 6・9.5s）", seconds: 9.5 },
    { file: "/se/lib/fireworks/v4-2.mp3", title: "fireworks ミックス 2（12 素材・うちニコニ・コモンズ 4・9.5s）", seconds: 9.5 },
    { file: "/se/lib/fireworks/v4-3.mp3", title: "fireworks ミックス 3（12 素材・うちニコニ・コモンズ 7・9.5s）", seconds: 9.5 },
    { file: "/se/lib/fireworks/v4-4.mp3", title: "fireworks ミックス 4（12 素材・うちニコニ・コモンズ 3・9.5s）", seconds: 9.5 },
    { file: "/se/lib/fireworks/v4-5.mp3", title: "fireworks ミックス 5（12 素材・うちニコニ・コモンズ 4・9.5s）", seconds: 9.5 },
  ],
  "fanfare": [
    { file: "/se/lib/fanfare/v4-1.mp3", title: "fanfare ミックス 1（12 素材・うちニコニ・コモンズ 7・8.5s）", seconds: 8.54 },
    { file: "/se/lib/fanfare/v4-2.mp3", title: "fanfare ミックス 2（12 素材・うちニコニ・コモンズ 6・9.5s）", seconds: 9.5 },
    { file: "/se/lib/fanfare/v4-3.mp3", title: "fanfare ミックス 3（12 素材・うちニコニ・コモンズ 4・9.5s）", seconds: 9.5 },
    { file: "/se/lib/fanfare/v4-4.mp3", title: "fanfare ミックス 4（12 素材・うちニコニ・コモンズ 5・9.5s）", seconds: 9.5 },
    { file: "/se/lib/fanfare/v4-5.mp3", title: "fanfare ミックス 5（12 素材・うちニコニ・コモンズ 7・9.5s）", seconds: 9.5 },
  ],
  "win": [
    { file: "/se/lib/win/v4-1.mp3", title: "win ミックス 1（8 素材・うちニコニ・コモンズ 3・6.5s）", seconds: 6.5 },
    { file: "/se/lib/win/v4-2.mp3", title: "win ミックス 2（8 素材・うちニコニ・コモンズ 3・5.2s）", seconds: 5.25 },
    { file: "/se/lib/win/v4-3.mp3", title: "win ミックス 3（8 素材・うちニコニ・コモンズ 4・5.1s）", seconds: 5.14 },
    { file: "/se/lib/win/v4-4.mp3", title: "win ミックス 4（9 素材・うちニコニ・コモンズ 7・6.5s）", seconds: 6.5 },
    { file: "/se/lib/win/v4-5.mp3", title: "win ミックス 5（8 素材・うちニコニ・コモンズ 2・5.0s）", seconds: 4.95 },
  ],
  "jackpot": [
    { file: "/se/lib/jackpot/v4-1.mp3", title: "jackpot ミックス 1（13 素材・うちニコニ・コモンズ 5・9.5s）", seconds: 9.5 },
    { file: "/se/lib/jackpot/v4-2.mp3", title: "jackpot ミックス 2（13 素材・うちニコニ・コモンズ 6・9.2s）", seconds: 9.16 },
    { file: "/se/lib/jackpot/v4-3.mp3", title: "jackpot ミックス 3（13 素材・うちニコニ・コモンズ 6・9.5s）", seconds: 9.5 },
    { file: "/se/lib/jackpot/v4-4.mp3", title: "jackpot ミックス 4（13 素材・うちニコニ・コモンズ 5・9.0s）", seconds: 9.04 },
    { file: "/se/lib/jackpot/v4-5.mp3", title: "jackpot ミックス 5（13 素材・うちニコニ・コモンズ 6・9.5s）", seconds: 9.5 },
  ],
  "coin": [
    { file: "/se/lib/coin/v4-1.mp3", title: "coin ミックス 1（11 素材・うちニコニ・コモンズ 4・5.9s）", seconds: 5.86 },
    { file: "/se/lib/coin/v4-2.mp3", title: "coin ミックス 2（8 素材・うちニコニ・コモンズ 4・5.0s）", seconds: 5.04 },
    { file: "/se/lib/coin/v4-3.mp3", title: "coin ミックス 3（8 素材・うちニコニ・コモンズ 4・6.5s）", seconds: 6.5 },
    { file: "/se/lib/coin/v4-4.mp3", title: "coin ミックス 4（8 素材・うちニコニ・コモンズ 2・5.5s）", seconds: 5.48 },
    { file: "/se/lib/coin/v4-5.mp3", title: "coin ミックス 5（8 素材・うちニコニ・コモンズ 4・5.1s）", seconds: 5.1 },
  ],
  "cheer": [
    { file: "/se/lib/cheer/v4-1.mp3", title: "cheer ミックス 1（12 素材・うちニコニ・コモンズ 5・9.5s）", seconds: 9.5 },
    { file: "/se/lib/cheer/v4-2.mp3", title: "cheer ミックス 2（12 素材・うちニコニ・コモンズ 7・8.5s）", seconds: 8.54 },
    { file: "/se/lib/cheer/v4-3.mp3", title: "cheer ミックス 3（12 素材・うちニコニ・コモンズ 8・9.3s）", seconds: 9.33 },
    { file: "/se/lib/cheer/v4-4.mp3", title: "cheer ミックス 4（12 素材・うちニコニ・コモンズ 4・9.5s）", seconds: 9.5 },
    { file: "/se/lib/cheer/v4-5.mp3", title: "cheer ミックス 5（12 素材・うちニコニ・コモンズ 7・9.5s）", seconds: 9.5 },
  ],
  "sparkle": [
    { file: "/se/lib/sparkle/v4-1.mp3", title: "sparkle ミックス 1（9 素材・うちニコニ・コモンズ 5・5.3s）", seconds: 5.33 },
    { file: "/se/lib/sparkle/v4-2.mp3", title: "sparkle ミックス 2（8 素材・うちニコニ・コモンズ 3・5.8s）", seconds: 5.81 },
    { file: "/se/lib/sparkle/v4-3.mp3", title: "sparkle ミックス 3（9 素材・うちニコニ・コモンズ 3・6.5s）", seconds: 6.5 },
    { file: "/se/lib/sparkle/v4-4.mp3", title: "sparkle ミックス 4（8 素材・うちニコニ・コモンズ 4・6.5s）", seconds: 6.5 },
    { file: "/se/lib/sparkle/v4-5.mp3", title: "sparkle ミックス 5（9 素材・うちニコニ・コモンズ 4・6.5s）", seconds: 6.5 },
  ],
  "magic": [
    { file: "/se/lib/magic/v4-1.mp3", title: "magic ミックス 1（8 素材・うちニコニ・コモンズ 4・6.5s）", seconds: 6.47 },
    { file: "/se/lib/magic/v4-2.mp3", title: "magic ミックス 2（8 素材・うちニコニ・コモンズ 3・6.2s）", seconds: 6.17 },
    { file: "/se/lib/magic/v4-3.mp3", title: "magic ミックス 3（8 素材・うちニコニ・コモンズ 4・6.5s）", seconds: 6.5 },
    { file: "/se/lib/magic/v4-4.mp3", title: "magic ミックス 4（8 素材・うちニコニ・コモンズ 4・6.5s）", seconds: 6.5 },
    { file: "/se/lib/magic/v4-5.mp3", title: "magic ミックス 5（8 素材・うちニコニ・コモンズ 4・6.5s）", seconds: 6.5 },
  ],
  "heart": [
    { file: "/se/lib/heart/v4-1.mp3", title: "heart ミックス 1（11 素材・うちニコニ・コモンズ 4・5.2s）", seconds: 5.22 },
    { file: "/se/lib/heart/v4-2.mp3", title: "heart ミックス 2（8 素材・うちニコニ・コモンズ 4・5.5s）", seconds: 5.53 },
    { file: "/se/lib/heart/v4-3.mp3", title: "heart ミックス 3（10 素材・うちニコニ・コモンズ 7・5.8s）", seconds: 5.85 },
    { file: "/se/lib/heart/v4-4.mp3", title: "heart ミックス 4（9 素材・うちニコニ・コモンズ 5・5.6s）", seconds: 5.64 },
    { file: "/se/lib/heart/v4-5.mp3", title: "heart ミックス 5（9 素材・うちニコニ・コモンズ 3・6.5s）", seconds: 6.5 },
  ],
  "balloon": [
    { file: "/se/lib/balloon/v4-1.mp3", title: "balloon ミックス 1（5 素材・うちニコニ・コモンズ 3・3.5s）", seconds: 3.5 },
    { file: "/se/lib/balloon/v4-2.mp3", title: "balloon ミックス 2（4 素材・うちニコニ・コモンズ 3・3.2s）", seconds: 3.2 },
    { file: "/se/lib/balloon/v4-3.mp3", title: "balloon ミックス 3（4 素材・うちニコニ・コモンズ 3・3.4s）", seconds: 3.37 },
    { file: "/se/lib/balloon/v4-4.mp3", title: "balloon ミックス 4（5 素材・うちニコニ・コモンズ 2・3.4s）", seconds: 3.42 },
    { file: "/se/lib/balloon/v4-5.mp3", title: "balloon ミックス 5（4 素材・うちニコニ・コモンズ 3・3.5s）", seconds: 3.5 },
  ],
  "cat": [
    { file: "/se/lib/cat/v4-1.mp3", title: "cat ミックス 1（8 素材・うちニコニ・コモンズ 4・6.2s）", seconds: 6.19 },
    { file: "/se/lib/cat/v4-2.mp3", title: "cat ミックス 2（8 素材・うちニコニ・コモンズ 5・6.5s）", seconds: 6.48 },
    { file: "/se/lib/cat/v4-3.mp3", title: "cat ミックス 3（9 素材・うちニコニ・コモンズ 3・6.5s）", seconds: 6.5 },
    { file: "/se/lib/cat/v4-4.mp3", title: "cat ミックス 4（8 素材・うちニコニ・コモンズ 4・5.3s）", seconds: 5.35 },
    { file: "/se/lib/cat/v4-5.mp3", title: "cat ミックス 5（9 素材・うちニコニ・コモンズ 5・6.5s）", seconds: 6.5 },
  ],
  "dog": [
    { file: "/se/lib/dog/v4-1.mp3", title: "dog ミックス 1（8 素材・うちニコニ・コモンズ 3・5.1s）", seconds: 5.12 },
    { file: "/se/lib/dog/v4-2.mp3", title: "dog ミックス 2（8 素材・うちニコニ・コモンズ 5・6.5s）", seconds: 6.5 },
    { file: "/se/lib/dog/v4-3.mp3", title: "dog ミックス 3（9 素材・うちニコニ・コモンズ 5・6.5s）", seconds: 6.5 },
    { file: "/se/lib/dog/v4-4.mp3", title: "dog ミックス 4（8 素材・うちニコニ・コモンズ 3・6.5s）", seconds: 6.5 },
    { file: "/se/lib/dog/v4-5.mp3", title: "dog ミックス 5（8 素材・うちニコニ・コモンズ 4・5.1s）", seconds: 5.11 },
  ],
  "pig": [
    { file: "/se/lib/pig/v4-1.mp3", title: "pig ミックス 1（9 素材・うちニコニ・コモンズ 2・5.5s）", seconds: 5.51 },
    { file: "/se/lib/pig/v4-2.mp3", title: "pig ミックス 2（8 素材・うちニコニ・コモンズ 1・5.1s）", seconds: 5.06 },
    { file: "/se/lib/pig/v4-3.mp3", title: "pig ミックス 3（9 素材・うちニコニ・コモンズ 1・6.1s）", seconds: 6.06 },
    { file: "/se/lib/pig/v4-4.mp3", title: "pig ミックス 4（9 素材・うちニコニ・コモンズ 3・6.5s）", seconds: 6.5 },
    { file: "/se/lib/pig/v4-5.mp3", title: "pig ミックス 5（9 素材・うちニコニ・コモンズ 3・6.5s）", seconds: 6.5 },
  ],
  "elephant": [
    { file: "/se/lib/elephant/v4-1.mp3", title: "elephant ミックス 1（8 素材・うちニコニ・コモンズ 4・6.5s）", seconds: 6.5 },
    { file: "/se/lib/elephant/v4-2.mp3", title: "elephant ミックス 2（8 素材・うちニコニ・コモンズ 4・6.5s）", seconds: 6.5 },
    { file: "/se/lib/elephant/v4-3.mp3", title: "elephant ミックス 3（8 素材・うちニコニ・コモンズ 3・6.2s）", seconds: 6.23 },
    { file: "/se/lib/elephant/v4-4.mp3", title: "elephant ミックス 4（8 素材・うちニコニ・コモンズ 4・6.2s）", seconds: 6.22 },
    { file: "/se/lib/elephant/v4-5.mp3", title: "elephant ミックス 5（8 素材・うちニコニ・コモンズ 1・5.9s）", seconds: 5.89 },
  ],
  "wolf": [
    { file: "/se/lib/wolf/v4-1.mp3", title: "wolf ミックス 1（9 素材・うちニコニ・コモンズ 1・5.7s）", seconds: 5.66 },
    { file: "/se/lib/wolf/v4-2.mp3", title: "wolf ミックス 2（8 素材・うちニコニ・コモンズ 4・6.0s）", seconds: 6.05 },
    { file: "/se/lib/wolf/v4-3.mp3", title: "wolf ミックス 3（9 素材・うちニコニ・コモンズ 3・6.5s）", seconds: 6.5 },
    { file: "/se/lib/wolf/v4-4.mp3", title: "wolf ミックス 4（8 素材・うちニコニ・コモンズ 1・6.0s）", seconds: 5.97 },
    { file: "/se/lib/wolf/v4-5.mp3", title: "wolf ミックス 5（8 素材・うちニコニ・コモンズ 2・6.2s）", seconds: 6.2 },
  ],
  "lion": [
    { file: "/se/lib/lion/v4-1.mp3", title: "lion ミックス 1（12 素材・うちニコニ・コモンズ 5・7.7s）", seconds: 7.68 },
    { file: "/se/lib/lion/v4-2.mp3", title: "lion ミックス 2（12 素材・うちニコニ・コモンズ 6・9.5s）", seconds: 9.5 },
    { file: "/se/lib/lion/v4-3.mp3", title: "lion ミックス 3（12 素材・うちニコニ・コモンズ 6・9.3s）", seconds: 9.34 },
    { file: "/se/lib/lion/v4-4.mp3", title: "lion ミックス 4（12 素材・うちニコニ・コモンズ 4・9.5s）", seconds: 9.5 },
    { file: "/se/lib/lion/v4-5.mp3", title: "lion ミックス 5（12 素材・うちニコニ・コモンズ 3・9.4s）", seconds: 9.39 },
  ],
  "bird": [
    { file: "/se/lib/bird/v4-1.mp3", title: "bird ミックス 1（4 素材・うちニコニ・コモンズ 1・3.5s）", seconds: 3.5 },
    { file: "/se/lib/bird/v4-2.mp3", title: "bird ミックス 2（4 素材・うちニコニ・コモンズ 2・3.5s）", seconds: 3.5 },
    { file: "/se/lib/bird/v4-3.mp3", title: "bird ミックス 3（4 素材・うちニコニ・コモンズ 1・3.3s）", seconds: 3.35 },
    { file: "/se/lib/bird/v4-4.mp3", title: "bird ミックス 4（5 素材・うちニコニ・コモンズ 2・3.5s）", seconds: 3.5 },
    { file: "/se/lib/bird/v4-5.mp3", title: "bird ミックス 5（4 素材・うちニコニ・コモンズ 3・3.5s）", seconds: 3.5 },
  ],
  "horse": [
    { file: "/se/lib/horse/v4-1.mp3", title: "horse ミックス 1（8 素材・うちニコニ・コモンズ 3・6.5s）", seconds: 6.5 },
    { file: "/se/lib/horse/v4-2.mp3", title: "horse ミックス 2（8 素材・うちニコニ・コモンズ 4・6.5s）", seconds: 6.5 },
    { file: "/se/lib/horse/v4-3.mp3", title: "horse ミックス 3（8 素材・うちニコニ・コモンズ 4・5.7s）", seconds: 5.72 },
    { file: "/se/lib/horse/v4-4.mp3", title: "horse ミックス 4（8 素材・うちニコニ・コモンズ 3・6.5s）", seconds: 6.5 },
    { file: "/se/lib/horse/v4-5.mp3", title: "horse ミックス 5（8 素材・うちニコニ・コモンズ 3・6.1s）", seconds: 6.13 },
  ],
  "cow": [
    { file: "/se/lib/cow/v4-1.mp3", title: "cow ミックス 1（8 素材・うちニコニ・コモンズ 2・6.5s）", seconds: 6.5 },
    { file: "/se/lib/cow/v4-2.mp3", title: "cow ミックス 2（8 素材・うちニコニ・コモンズ 4・6.0s）", seconds: 6.01 },
    { file: "/se/lib/cow/v4-3.mp3", title: "cow ミックス 3（8 素材・うちニコニ・コモンズ 4・5.9s）", seconds: 5.94 },
    { file: "/se/lib/cow/v4-4.mp3", title: "cow ミックス 4（9 素材・うちニコニ・コモンズ 7・5.3s）", seconds: 5.3 },
    { file: "/se/lib/cow/v4-5.mp3", title: "cow ミックス 5（8 素材・うちニコニ・コモンズ 4・5.5s）", seconds: 5.5 },
  ],
  "monkey": [
    { file: "/se/lib/monkey/v4-1.mp3", title: "monkey ミックス 1（8 素材・うちニコニ・コモンズ 3・5.4s）", seconds: 5.38 },
    { file: "/se/lib/monkey/v4-2.mp3", title: "monkey ミックス 2（8 素材・うちニコニ・コモンズ 2・6.5s）", seconds: 6.5 },
    { file: "/se/lib/monkey/v4-3.mp3", title: "monkey ミックス 3（8 素材・うちニコニ・コモンズ 3・5.2s）", seconds: 5.22 },
    { file: "/se/lib/monkey/v4-4.mp3", title: "monkey ミックス 4（8 素材・うちニコニ・コモンズ 2・5.4s）", seconds: 5.38 },
    { file: "/se/lib/monkey/v4-5.mp3", title: "monkey ミックス 5（8 素材・うちニコニ・コモンズ 2・6.1s）", seconds: 6.11 },
  ],
  "bear": [
    { file: "/se/lib/bear/v4-1.mp3", title: "bear ミックス 1（9 素材・うちニコニ・コモンズ 4・6.5s）", seconds: 6.5 },
    { file: "/se/lib/bear/v4-2.mp3", title: "bear ミックス 2（10 素材・うちニコニ・コモンズ 5・5.4s）", seconds: 5.45 },
    { file: "/se/lib/bear/v4-3.mp3", title: "bear ミックス 3（9 素材・うちニコニ・コモンズ 2・6.5s）", seconds: 6.5 },
    { file: "/se/lib/bear/v4-4.mp3", title: "bear ミックス 4（8 素材・うちニコニ・コモンズ 1・5.5s）", seconds: 5.45 },
    { file: "/se/lib/bear/v4-5.mp3", title: "bear ミックス 5（8 素材・うちニコニ・コモンズ 4・6.5s）", seconds: 6.5 },
  ],
  "cute": [
    { file: "/se/lib/cute/v4-1.mp3", title: "cute ミックス 1（4 素材・うちニコニ・コモンズ 2・3.5s）", seconds: 3.5 },
    { file: "/se/lib/cute/v4-2.mp3", title: "cute ミックス 2（5 素材・うちニコニ・コモンズ 2・3.2s）", seconds: 3.25 },
    { file: "/se/lib/cute/v4-3.mp3", title: "cute ミックス 3（4 素材・うちニコニ・コモンズ 1・3.3s）", seconds: 3.26 },
    { file: "/se/lib/cute/v4-4.mp3", title: "cute ミックス 4（4 素材・うちニコニ・コモンズ 3・3.5s）", seconds: 3.5 },
    { file: "/se/lib/cute/v4-5.mp3", title: "cute ミックス 5（4 素材・うちニコニ・コモンズ 2・2.8s）", seconds: 2.81 },
  ],
  "drink": [
    { file: "/se/lib/drink/v4-1.mp3", title: "drink ミックス 1（8 素材・うちニコニ・コモンズ 3・6.2s）", seconds: 6.15 },
    { file: "/se/lib/drink/v4-2.mp3", title: "drink ミックス 2（9 素材・うちニコニ・コモンズ 4・5.8s）", seconds: 5.82 },
    { file: "/se/lib/drink/v4-3.mp3", title: "drink ミックス 3（8 素材・うちニコニ・コモンズ 3・5.9s）", seconds: 5.87 },
    { file: "/se/lib/drink/v4-4.mp3", title: "drink ミックス 4（11 素材・うちニコニ・コモンズ 3・6.5s）", seconds: 6.5 },
    { file: "/se/lib/drink/v4-5.mp3", title: "drink ミックス 5（9 素材・うちニコニ・コモンズ 5・5.6s）", seconds: 5.57 },
  ],
  "food": [
    { file: "/se/lib/food/v4-1.mp3", title: "food ミックス 1（4 素材・うちニコニ・コモンズ 2・3.5s）", seconds: 3.5 },
    { file: "/se/lib/food/v4-2.mp3", title: "food ミックス 2（4 素材・うちニコニ・コモンズ 2・3.0s）", seconds: 3.04 },
    { file: "/se/lib/food/v4-3.mp3", title: "food ミックス 3（4 素材・うちニコニ・コモンズ 3・2.9s）", seconds: 2.88 },
    { file: "/se/lib/food/v4-4.mp3", title: "food ミックス 4（4 素材・うちニコニ・コモンズ 1・2.9s）", seconds: 2.89 },
    { file: "/se/lib/food/v4-5.mp3", title: "food ミックス 5（4 素材・うちニコニ・コモンズ 3・3.5s）", seconds: 3.5 },
  ],
  "party": [
    { file: "/se/lib/party/v4-1.mp3", title: "party ミックス 1（12 素材・うちニコニ・コモンズ 6・9.5s）", seconds: 9.5 },
    { file: "/se/lib/party/v4-2.mp3", title: "party ミックス 2（13 素材・うちニコニ・コモンズ 8・9.5s）", seconds: 9.5 },
    { file: "/se/lib/party/v4-3.mp3", title: "party ミックス 3（12 素材・うちニコニ・コモンズ 7・9.5s）", seconds: 9.5 },
    { file: "/se/lib/party/v4-4.mp3", title: "party ミックス 4（12 素材・うちニコニ・コモンズ 7・7.9s）", seconds: 7.9 },
    { file: "/se/lib/party/v4-5.mp3", title: "party ミックス 5（12 素材・うちニコニ・コモンズ 5・9.4s）", seconds: 9.37 },
  ],
  "bell": [
    { file: "/se/lib/bell/v4-1.mp3", title: "bell ミックス 1（8 素材・うちニコニ・コモンズ 2・6.3s）", seconds: 6.27 },
    { file: "/se/lib/bell/v4-2.mp3", title: "bell ミックス 2（8 素材・うちニコニ・コモンズ 2・5.1s）", seconds: 5.14 },
    { file: "/se/lib/bell/v4-3.mp3", title: "bell ミックス 3（8 素材・うちニコニ・コモンズ 2・6.3s）", seconds: 6.34 },
    { file: "/se/lib/bell/v4-4.mp3", title: "bell ミックス 4（9 素材・うちニコニ・コモンズ 6・6.5s）", seconds: 6.5 },
    { file: "/se/lib/bell/v4-5.mp3", title: "bell ミックス 5（8 素材・うちニコニ・コモンズ 4・5.5s）", seconds: 5.53 },
  ],
  "christmas": [
    { file: "/se/lib/christmas/v4-1.mp3", title: "christmas ミックス 1（9 素材・うちニコニ・コモンズ 5・6.5s）", seconds: 6.5 },
    { file: "/se/lib/christmas/v4-2.mp3", title: "christmas ミックス 2（8 素材・うちニコニ・コモンズ 3・6.5s）", seconds: 6.5 },
    { file: "/se/lib/christmas/v4-3.mp3", title: "christmas ミックス 3（8 素材・うちニコニ・コモンズ 2・6.0s）", seconds: 6.05 },
    { file: "/se/lib/christmas/v4-4.mp3", title: "christmas ミックス 4（9 素材・うちニコニ・コモンズ 5・6.5s）", seconds: 6.5 },
    { file: "/se/lib/christmas/v4-5.mp3", title: "christmas ミックス 5（8 素材・うちニコニ・コモンズ 3・5.5s）", seconds: 5.53 },
  ],
  "halloween": [
    { file: "/se/lib/halloween/v4-1.mp3", title: "halloween ミックス 1（9 素材・うちニコニ・コモンズ 2・6.4s）", seconds: 6.45 },
    { file: "/se/lib/halloween/v4-2.mp3", title: "halloween ミックス 2（9 素材・うちニコニ・コモンズ 3・6.5s）", seconds: 6.5 },
    { file: "/se/lib/halloween/v4-3.mp3", title: "halloween ミックス 3（9 素材・うちニコニ・コモンズ 3・4.9s）", seconds: 4.94 },
    { file: "/se/lib/halloween/v4-4.mp3", title: "halloween ミックス 4（8 素材・うちニコニ・コモンズ 4・6.4s）", seconds: 6.36 },
    { file: "/se/lib/halloween/v4-5.mp3", title: "halloween ミックス 5（8 素材・うちニコニ・コモンズ 3・6.3s）", seconds: 6.34 },
  ],
  "sea": [
    { file: "/se/lib/sea/v4-1.mp3", title: "sea ミックス 1（8 素材・うちニコニ・コモンズ 2・5.6s）", seconds: 5.59 },
    { file: "/se/lib/sea/v4-2.mp3", title: "sea ミックス 2（8 素材・うちニコニ・コモンズ 2・5.4s）", seconds: 5.44 },
    { file: "/se/lib/sea/v4-3.mp3", title: "sea ミックス 3（9 素材・うちニコニ・コモンズ 3・6.5s）", seconds: 6.5 },
    { file: "/se/lib/sea/v4-4.mp3", title: "sea ミックス 4（8 素材・うちニコニ・コモンズ 3・5.4s）", seconds: 5.41 },
    { file: "/se/lib/sea/v4-5.mp3", title: "sea ミックス 5（8 素材・うちニコニ・コモンズ 2・6.5s）", seconds: 6.5 },
  ],
  "rocket": [
    { file: "/se/lib/rocket/v4-1.mp3", title: "rocket ミックス 1（12 素材・うちニコニ・コモンズ 6・9.5s）", seconds: 9.5 },
    { file: "/se/lib/rocket/v4-2.mp3", title: "rocket ミックス 2（12 素材・うちニコニ・コモンズ 6・9.5s）", seconds: 9.5 },
    { file: "/se/lib/rocket/v4-3.mp3", title: "rocket ミックス 3（12 素材・うちニコニ・コモンズ 5・8.3s）", seconds: 8.34 },
    { file: "/se/lib/rocket/v4-4.mp3", title: "rocket ミックス 4（12 素材・うちニコニ・コモンズ 6・8.5s）", seconds: 8.53 },
    { file: "/se/lib/rocket/v4-5.mp3", title: "rocket ミックス 5（12 素材・うちニコニ・コモンズ 6・9.5s）", seconds: 9.5 },
  ],
  "explosion": [
    { file: "/se/lib/explosion/v4-1.mp3", title: "explosion ミックス 1（12 素材・うちニコニ・コモンズ 4・9.4s）", seconds: 9.38 },
    { file: "/se/lib/explosion/v4-2.mp3", title: "explosion ミックス 2（12 素材・うちニコニ・コモンズ 6・9.5s）", seconds: 9.5 },
    { file: "/se/lib/explosion/v4-3.mp3", title: "explosion ミックス 3（12 素材・うちニコニ・コモンズ 6・9.5s）", seconds: 9.5 },
    { file: "/se/lib/explosion/v4-4.mp3", title: "explosion ミックス 4（12 素材・うちニコニ・コモンズ 6・9.5s）", seconds: 9.5 },
    { file: "/se/lib/explosion/v4-5.mp3", title: "explosion ミックス 5（12 素材・うちニコニ・コモンズ 5・9.5s）", seconds: 9.5 },
  ],
  "casino": [
    { file: "/se/lib/casino/v4-1.mp3", title: "casino ミックス 1（13 素材・うちニコニ・コモンズ 6・9.5s）", seconds: 9.5 },
    { file: "/se/lib/casino/v4-2.mp3", title: "casino ミックス 2（13 素材・うちニコニ・コモンズ 4・9.5s）", seconds: 9.5 },
    { file: "/se/lib/casino/v4-3.mp3", title: "casino ミックス 3（13 素材・うちニコニ・コモンズ 5・8.9s）", seconds: 8.92 },
    { file: "/se/lib/casino/v4-4.mp3", title: "casino ミックス 4（13 素材・うちニコニ・コモンズ 6・9.5s）", seconds: 9.5 },
    { file: "/se/lib/casino/v4-5.mp3", title: "casino ミックス 5（13 素材・うちニコニ・コモンズ 8・8.5s）", seconds: 8.52 },
  ],
  "music": [
    { file: "/se/lib/music/v4-1.mp3", title: "music ミックス 1（9 素材・うちニコニ・コモンズ 3・6.2s）", seconds: 6.25 },
    { file: "/se/lib/music/v4-2.mp3", title: "music ミックス 2（8 素材・うちニコニ・コモンズ 4・6.5s）", seconds: 6.5 },
    { file: "/se/lib/music/v4-3.mp3", title: "music ミックス 3（8 素材・うちニコニ・コモンズ 3・5.0s）", seconds: 5.03 },
    { file: "/se/lib/music/v4-4.mp3", title: "music ミックス 4（8 素材・うちニコニ・コモンズ 5・6.5s）", seconds: 6.5 },
    { file: "/se/lib/music/v4-5.mp3", title: "music ミックス 5（8 素材・うちニコニ・コモンズ 4・5.9s）", seconds: 5.94 },
  ],
  "battle": [
    { file: "/se/lib/battle/v4-1.mp3", title: "battle ミックス 1（12 素材・うちニコニ・コモンズ 5・9.4s）", seconds: 9.41 },
    { file: "/se/lib/battle/v4-2.mp3", title: "battle ミックス 2（12 素材・うちニコニ・コモンズ 3・7.6s）", seconds: 7.57 },
    { file: "/se/lib/battle/v4-3.mp3", title: "battle ミックス 3（12 素材・うちニコニ・コモンズ 7・8.5s）", seconds: 8.51 },
    { file: "/se/lib/battle/v4-4.mp3", title: "battle ミックス 4（13 素材・うちニコニ・コモンズ 7・8.9s）", seconds: 8.88 },
    { file: "/se/lib/battle/v4-5.mp3", title: "battle ミックス 5（12 素材・うちニコニ・コモンズ 6・8.2s）", seconds: 8.23 },
  ],
  "vehicle": [
    { file: "/se/lib/vehicle/v4-1.mp3", title: "vehicle ミックス 1（11 素材・うちニコニ・コモンズ 6・5.3s）", seconds: 5.31 },
    { file: "/se/lib/vehicle/v4-2.mp3", title: "vehicle ミックス 2（8 素材・うちニコニ・コモンズ 4・6.1s）", seconds: 6.08 },
    { file: "/se/lib/vehicle/v4-3.mp3", title: "vehicle ミックス 3（8 素材・うちニコニ・コモンズ 5・5.6s）", seconds: 5.62 },
    { file: "/se/lib/vehicle/v4-4.mp3", title: "vehicle ミックス 4（8 素材・うちニコニ・コモンズ 4・5.3s）", seconds: 5.28 },
    { file: "/se/lib/vehicle/v4-5.mp3", title: "vehicle ミックス 5（8 素材・うちニコニ・コモンズ 4・6.1s）", seconds: 6.08 },
  ],
  "flower": [
    { file: "/se/lib/flower/v4-1.mp3", title: "flower ミックス 1（8 素材・うちニコニ・コモンズ 3・5.0s）", seconds: 5.04 },
    { file: "/se/lib/flower/v4-2.mp3", title: "flower ミックス 2（8 素材・うちニコニ・コモンズ 3・6.5s）", seconds: 6.5 },
    { file: "/se/lib/flower/v4-3.mp3", title: "flower ミックス 3（8 素材・うちニコニ・コモンズ 4・6.5s）", seconds: 6.5 },
    { file: "/se/lib/flower/v4-4.mp3", title: "flower ミックス 4（8 素材・うちニコニ・コモンズ 4・6.5s）", seconds: 6.5 },
    { file: "/se/lib/flower/v4-5.mp3", title: "flower ミックス 5（11 素材・うちニコニ・コモンズ 7・5.5s）", seconds: 5.48 },
  ],
  "pop": [
    { file: "/se/lib/pop/v4-1.mp3", title: "pop ミックス 1（5 素材・うちニコニ・コモンズ 3・3.5s）", seconds: 3.5 },
    { file: "/se/lib/pop/v4-2.mp3", title: "pop ミックス 2（5 素材・うちニコニ・コモンズ 3・3.5s）", seconds: 3.5 },
    { file: "/se/lib/pop/v4-3.mp3", title: "pop ミックス 3（4 素材・うちニコニ・コモンズ 1・3.5s）", seconds: 3.5 },
    { file: "/se/lib/pop/v4-4.mp3", title: "pop ミックス 4（5 素材・うちニコニ・コモンズ 3・3.5s）", seconds: 3.5 },
    { file: "/se/lib/pop/v4-5.mp3", title: "pop ミックス 5（4 素材・うちニコニ・コモンズ 3・3.5s）", seconds: 3.45 },
  ],
  "trophy": [
    { file: "/se/lib/trophy/v4-1.mp3", title: "trophy ミックス 1（15 素材・うちニコニ・コモンズ 10・10.2s）", seconds: 10.21 },
    { file: "/se/lib/trophy/v4-2.mp3", title: "trophy ミックス 2（15 素材・うちニコニ・コモンズ 7・12.0s）", seconds: 12.0 },
    { file: "/se/lib/trophy/v4-3.mp3", title: "trophy ミックス 3（15 素材・うちニコニ・コモンズ 7・11.7s）", seconds: 11.68 },
    { file: "/se/lib/trophy/v4-4.mp3", title: "trophy ミックス 4（15 素材・うちニコニ・コモンズ 8・12.0s）", seconds: 12.0 },
    { file: "/se/lib/trophy/v4-5.mp3", title: "trophy ミックス 5（15 素材・うちニコニ・コモンズ 9・11.8s）", seconds: 11.82 },
  ],
  "epic": [
    { file: "/se/lib/epic/v4-1.mp3", title: "epic ミックス 1（15 素材・うちニコニ・コモンズ 11・12.6s）", seconds: 12.55 },
    { file: "/se/lib/epic/v4-2.mp3", title: "epic ミックス 2（15 素材・うちニコニ・コモンズ 8・12.5s）", seconds: 12.54 },
    { file: "/se/lib/epic/v4-3.mp3", title: "epic ミックス 3（15 素材・うちニコニ・コモンズ 8・12.6s）", seconds: 12.55 },
    { file: "/se/lib/epic/v4-4.mp3", title: "epic ミックス 4（15 素材・うちニコニ・コモンズ 10・13.5s）", seconds: 13.51 },
    { file: "/se/lib/epic/v4-5.mp3", title: "epic ミックス 5（15 素材・うちニコニ・コモンズ 8・14.8s）", seconds: 14.85 },
  ],
  "notify": [
    { file: "/se/lib/notify/v4-1.mp3", title: "notify ミックス 1（4 素材・うちニコニ・コモンズ 3・3.5s）", seconds: 3.5 },
    { file: "/se/lib/notify/v4-2.mp3", title: "notify ミックス 2（4 素材・うちニコニ・コモンズ 2・3.5s）", seconds: 3.5 },
    { file: "/se/lib/notify/v4-3.mp3", title: "notify ミックス 3（4 素材・うちニコニ・コモンズ 2・3.5s）", seconds: 3.5 },
    { file: "/se/lib/notify/v4-4.mp3", title: "notify ミックス 4（4 素材・うちニコニ・コモンズ 2・3.1s）", seconds: 3.09 },
    { file: "/se/lib/notify/v4-5.mp3", title: "notify ミックス 5（4 素材・うちニコニ・コモンズ 2・3.5s）", seconds: 3.5 },
  ],
  "wow": [
    { file: "/se/lib/wow/v4-1.mp3", title: "wow ミックス 1（12 素材・うちニコニ・コモンズ 6・9.5s）", seconds: 9.5 },
    { file: "/se/lib/wow/v4-2.mp3", title: "wow ミックス 2（12 素材・うちニコニ・コモンズ 5・9.5s）", seconds: 9.5 },
    { file: "/se/lib/wow/v4-3.mp3", title: "wow ミックス 3（12 素材・うちニコニ・コモンズ 6・9.5s）", seconds: 9.5 },
    { file: "/se/lib/wow/v4-4.mp3", title: "wow ミックス 4（12 素材・うちニコニ・コモンズ 4・9.5s）", seconds: 9.5 },
    { file: "/se/lib/wow/v4-5.mp3", title: "wow ミックス 5（12 素材・うちニコニ・コモンズ 4・9.5s）", seconds: 9.5 },
  ],
  "dice": [
    { file: "/se/lib/dice/v4-1.mp3", title: "dice ミックス 1（8 素材・うちニコニ・コモンズ 3・6.3s）", seconds: 6.27 },
    { file: "/se/lib/dice/v4-2.mp3", title: "dice ミックス 2（8 素材・うちニコニ・コモンズ 3・5.7s）", seconds: 5.72 },
    { file: "/se/lib/dice/v4-3.mp3", title: "dice ミックス 3（8 素材・うちニコニ・コモンズ 4・6.5s）", seconds: 6.5 },
    { file: "/se/lib/dice/v4-4.mp3", title: "dice ミックス 4（8 素材・うちニコニ・コモンズ 4・5.3s）", seconds: 5.25 },
    { file: "/se/lib/dice/v4-5.mp3", title: "dice ミックス 5（9 素材・うちニコニ・コモンズ 4・5.9s）", seconds: 5.94 },
  ],
  "kids": [
    { file: "/se/lib/kids/v4-1.mp3", title: "kids ミックス 1（4 素材・うちニコニ・コモンズ 2・3.5s）", seconds: 3.5 },
    { file: "/se/lib/kids/v4-2.mp3", title: "kids ミックス 2（4 素材・うちニコニ・コモンズ 2・3.5s）", seconds: 3.5 },
    { file: "/se/lib/kids/v4-3.mp3", title: "kids ミックス 3（4 素材・うちニコニ・コモンズ 2・3.5s）", seconds: 3.5 },
    { file: "/se/lib/kids/v4-4.mp3", title: "kids ミックス 4（4 素材・うちニコニ・コモンズ 2・3.3s）", seconds: 3.31 },
    { file: "/se/lib/kids/v4-5.mp3", title: "kids ミックス 5（4 素材・うちニコニ・コモンズ 2・3.5s）", seconds: 3.5 },
  ],
  "thunder": [
    { file: "/se/lib/thunder/v4-1.mp3", title: "thunder ミックス 1（12 素材・うちニコニ・コモンズ 8・9.5s）", seconds: 9.5 },
    { file: "/se/lib/thunder/v4-2.mp3", title: "thunder ミックス 2（12 素材・うちニコニ・コモンズ 6・9.5s）", seconds: 9.5 },
    { file: "/se/lib/thunder/v4-3.mp3", title: "thunder ミックス 3（12 素材・うちニコニ・コモンズ 4・9.5s）", seconds: 9.5 },
    { file: "/se/lib/thunder/v4-4.mp3", title: "thunder ミックス 4（12 素材・うちニコニ・コモンズ 7・9.5s）", seconds: 9.5 },
    { file: "/se/lib/thunder/v4-5.mp3", title: "thunder ミックス 5（12 素材・うちニコニ・コモンズ 7・9.5s）", seconds: 9.5 },
  ],
  "fire": [
    { file: "/se/lib/fire/v4-1.mp3", title: "fire ミックス 1（12 素材・うちニコニ・コモンズ 5・9.5s）", seconds: 9.5 },
    { file: "/se/lib/fire/v4-2.mp3", title: "fire ミックス 2（12 素材・うちニコニ・コモンズ 7・8.3s）", seconds: 8.29 },
    { file: "/se/lib/fire/v4-3.mp3", title: "fire ミックス 3（12 素材・うちニコニ・コモンズ 6・9.5s）", seconds: 9.5 },
    { file: "/se/lib/fire/v4-4.mp3", title: "fire ミックス 4（12 素材・うちニコニ・コモンズ 6・9.5s）", seconds: 9.5 },
    { file: "/se/lib/fire/v4-5.mp3", title: "fire ミックス 5（12 素材・うちニコニ・コモンズ 7・9.5s）", seconds: 9.5 },
  ],
  "laser": [
    { file: "/se/lib/laser/v4-1.mp3", title: "laser ミックス 1（10 素材・うちニコニ・コモンズ 7・5.2s）", seconds: 5.18 },
    { file: "/se/lib/laser/v4-2.mp3", title: "laser ミックス 2（8 素材・うちニコニ・コモンズ 4・6.5s）", seconds: 6.5 },
    { file: "/se/lib/laser/v4-3.mp3", title: "laser ミックス 3（8 素材・うちニコニ・コモンズ 3・5.7s）", seconds: 5.7 },
    { file: "/se/lib/laser/v4-4.mp3", title: "laser ミックス 4（8 素材・うちニコニ・コモンズ 3・5.5s）", seconds: 5.45 },
    { file: "/se/lib/laser/v4-5.mp3", title: "laser ミックス 5（8 素材・うちニコニ・コモンズ 3・6.5s）", seconds: 6.5 },
  ],
  "whoosh": [
    { file: "/se/lib/whoosh/v4-1.mp3", title: "whoosh ミックス 1（5 素材・うちニコニ・コモンズ 3・3.5s）", seconds: 3.5 },
    { file: "/se/lib/whoosh/v4-2.mp3", title: "whoosh ミックス 2（4 素材・うちニコニ・コモンズ 2・3.5s）", seconds: 3.5 },
    { file: "/se/lib/whoosh/v4-3.mp3", title: "whoosh ミックス 3（4 素材・うちニコニ・コモンズ 2・3.5s）", seconds: 3.5 },
    { file: "/se/lib/whoosh/v4-4.mp3", title: "whoosh ミックス 4（4 素材・うちニコニ・コモンズ 3・2.7s）", seconds: 2.7 },
    { file: "/se/lib/whoosh/v4-5.mp3", title: "whoosh ミックス 5（4 素材・うちニコニ・コモンズ 2・3.5s）", seconds: 3.5 },
  ],
  "bulk-COOL": [
    { file: "/se/lib/bulk-COOL/v4-1.mp3", title: "bulk-COOL ミックス 1（8 素材・うちニコニ・コモンズ 4・5.0s）", seconds: 5.01 },
    { file: "/se/lib/bulk-COOL/v4-2.mp3", title: "bulk-COOL ミックス 2（8 素材・うちニコニ・コモンズ 5・5.4s）", seconds: 5.36 },
    { file: "/se/lib/bulk-COOL/v4-3.mp3", title: "bulk-COOL ミックス 3（9 素材・うちニコニ・コモンズ 4・5.7s）", seconds: 5.73 },
    { file: "/se/lib/bulk-COOL/v4-4.mp3", title: "bulk-COOL ミックス 4（8 素材・うちニコニ・コモンズ 5・6.0s）", seconds: 6.0 },
    { file: "/se/lib/bulk-COOL/v4-5.mp3", title: "bulk-COOL ミックス 5（8 素材・うちニコニ・コモンズ 5・6.0s）", seconds: 6.0 },
  ],
  "bulk-GREAT": [
    { file: "/se/lib/bulk-GREAT/v4-1.mp3", title: "bulk-GREAT ミックス 1（12 素材・うちニコニ・コモンズ 6・9.0s）", seconds: 9.0 },
    { file: "/se/lib/bulk-GREAT/v4-2.mp3", title: "bulk-GREAT ミックス 2（12 素材・うちニコニ・コモンズ 8・9.0s）", seconds: 9.0 },
    { file: "/se/lib/bulk-GREAT/v4-3.mp3", title: "bulk-GREAT ミックス 3（12 素材・うちニコニ・コモンズ 7・9.0s）", seconds: 9.0 },
    { file: "/se/lib/bulk-GREAT/v4-4.mp3", title: "bulk-GREAT ミックス 4（12 素材・うちニコニ・コモンズ 8・9.0s）", seconds: 9.0 },
    { file: "/se/lib/bulk-GREAT/v4-5.mp3", title: "bulk-GREAT ミックス 5（12 素材・うちニコニ・コモンズ 7・9.0s）", seconds: 9.0 },
  ],
  "bulk-FANTASTIC": [
    { file: "/se/lib/bulk-FANTASTIC/v4-1.mp3", title: "bulk-FANTASTIC ミックス 1（16 素材・うちニコニ・コモンズ 6・12.0s）", seconds: 12.0 },
    { file: "/se/lib/bulk-FANTASTIC/v4-2.mp3", title: "bulk-FANTASTIC ミックス 2（16 素材・うちニコニ・コモンズ 7・12.0s）", seconds: 12.0 },
    { file: "/se/lib/bulk-FANTASTIC/v4-3.mp3", title: "bulk-FANTASTIC ミックス 3（16 素材・うちニコニ・コモンズ 7・12.0s）", seconds: 12.0 },
    { file: "/se/lib/bulk-FANTASTIC/v4-4.mp3", title: "bulk-FANTASTIC ミックス 4（16 素材・うちニコニ・コモンズ 6・12.0s）", seconds: 12.0 },
    { file: "/se/lib/bulk-FANTASTIC/v4-5.mp3", title: "bulk-FANTASTIC ミックス 5（16 素材・うちニコニ・コモンズ 9・12.0s）", seconds: 12.0 },
  ],
  "bulk-MIRACLE": [
    { file: "/se/lib/bulk-MIRACLE/v4-1.mp3", title: "bulk-MIRACLE ミックス 1（16 素材・うちニコニ・コモンズ 12・14.3s）", seconds: 14.31 },
    { file: "/se/lib/bulk-MIRACLE/v4-2.mp3", title: "bulk-MIRACLE ミックス 2（16 素材・うちニコニ・コモンズ 11・14.1s）", seconds: 14.06 },
    { file: "/se/lib/bulk-MIRACLE/v4-3.mp3", title: "bulk-MIRACLE ミックス 3（16 素材・うちニコニ・コモンズ 9・15.0s）", seconds: 15.0 },
    { file: "/se/lib/bulk-MIRACLE/v4-4.mp3", title: "bulk-MIRACLE ミックス 4（16 素材・うちニコニ・コモンズ 6・14.6s）", seconds: 14.6 },
    { file: "/se/lib/bulk-MIRACLE/v4-5.mp3", title: "bulk-MIRACLE ミックス 5（16 素材・うちニコニ・コモンズ 7・14.7s）", seconds: 14.7 },
  ],
  "tier-T0": [
    { file: "/se/lib/tier-T0/v5-1.mp3", title: "tier-T0 控えめ 1（「スポッ」抜ける音・ポップ音・0.2s）", seconds: 0.24 },
    { file: "/se/lib/tier-T0/v5-2.mp3", title: "tier-T0 控えめ 2（アクセント効果音、キラン・0.8s）", seconds: 0.84 },
    { file: "/se/lib/tier-T0/v5-3.mp3", title: "tier-T0 控えめ 3（【SE】決定音３・0.5s）", seconds: 0.55 },
    { file: "/se/lib/tier-T0/v5-4.mp3", title: "tier-T0 控えめ 4（Bubble pop up alert noti・0.4s）", seconds: 0.38 },
    { file: "/se/lib/tier-T0/v5-5.mp3", title: "tier-T0 控えめ 5（【効果音】キュピーン♪・1.0s）", seconds: 1.0 },
  ],
  "tier-T1": [
    { file: "/se/lib/tier-T1/v4-1.mp3", title: "tier-T1 ミックス 1（4 素材・うちニコニ・コモンズ 1・4.0s）", seconds: 4.0 },
    { file: "/se/lib/tier-T1/v4-2.mp3", title: "tier-T1 ミックス 2（4 素材・うちニコニ・コモンズ 2・4.0s）", seconds: 4.0 },
    { file: "/se/lib/tier-T1/v4-3.mp3", title: "tier-T1 ミックス 3（4 素材・うちニコニ・コモンズ 3・4.0s）", seconds: 4.0 },
    { file: "/se/lib/tier-T1/v4-4.mp3", title: "tier-T1 ミックス 4（4 素材・うちニコニ・コモンズ 3・4.0s）", seconds: 4.0 },
    { file: "/se/lib/tier-T1/v4-5.mp3", title: "tier-T1 ミックス 5（4 素材・うちニコニ・コモンズ 3・3.5s）", seconds: 3.54 },
  ],
  "tier-T2": [
    { file: "/se/lib/tier-T2/v4-1.mp3", title: "tier-T2 ミックス 1（10 素材・うちニコニ・コモンズ 6・4.7s）", seconds: 4.72 },
    { file: "/se/lib/tier-T2/v4-2.mp3", title: "tier-T2 ミックス 2（8 素材・うちニコニ・コモンズ 4・5.2s）", seconds: 5.17 },
    { file: "/se/lib/tier-T2/v4-3.mp3", title: "tier-T2 ミックス 3（9 素材・うちニコニ・コモンズ 4・4.9s）", seconds: 4.89 },
    { file: "/se/lib/tier-T2/v4-4.mp3", title: "tier-T2 ミックス 4（8 素材・うちニコニ・コモンズ 5・6.0s）", seconds: 5.99 },
    { file: "/se/lib/tier-T2/v4-5.mp3", title: "tier-T2 ミックス 5（9 素材・うちニコニ・コモンズ 7・6.0s）", seconds: 6.0 },
  ],
  "tier-T3": [
    { file: "/se/lib/tier-T3/v4-1.mp3", title: "tier-T3 ミックス 1（12 素材・うちニコニ・コモンズ 8・9.0s）", seconds: 9.0 },
    { file: "/se/lib/tier-T3/v4-2.mp3", title: "tier-T3 ミックス 2（12 素材・うちニコニ・コモンズ 4・9.0s）", seconds: 9.0 },
    { file: "/se/lib/tier-T3/v4-3.mp3", title: "tier-T3 ミックス 3（12 素材・うちニコニ・コモンズ 3・9.0s）", seconds: 9.0 },
    { file: "/se/lib/tier-T3/v4-4.mp3", title: "tier-T3 ミックス 4（12 素材・うちニコニ・コモンズ 5・9.0s）", seconds: 9.0 },
    { file: "/se/lib/tier-T3/v4-5.mp3", title: "tier-T3 ミックス 5（12 素材・うちニコニ・コモンズ 5・9.0s）", seconds: 9.0 },
  ],
  "tier-T4": [
    { file: "/se/lib/tier-T4/v4-1.mp3", title: "tier-T4 ミックス 1（16 素材・うちニコニ・コモンズ 9・13.7s）", seconds: 13.7 },
    { file: "/se/lib/tier-T4/v4-2.mp3", title: "tier-T4 ミックス 2（16 素材・うちニコニ・コモンズ 6・13.2s）", seconds: 13.19 },
    { file: "/se/lib/tier-T4/v4-3.mp3", title: "tier-T4 ミックス 3（16 素材・うちニコニ・コモンズ 6・13.1s）", seconds: 13.07 },
    { file: "/se/lib/tier-T4/v4-4.mp3", title: "tier-T4 ミックス 4（16 素材・うちニコニ・コモンズ 10・12.0s）", seconds: 12.02 },
    { file: "/se/lib/tier-T4/v4-5.mp3", title: "tier-T4 ミックス 5（16 素材・うちニコニ・コモンズ 7・14.4s）", seconds: 14.45 },
  ],
  "hit": [
    { file: "/se/lib/hit/v4-1.mp3", title: "hit ミックス 1（13 素材・うちニコニ・コモンズ 6・10.0s）", seconds: 10.0 },
    { file: "/se/lib/hit/v4-2.mp3", title: "hit ミックス 2（13 素材・うちニコニ・コモンズ 7・10.0s）", seconds: 10.0 },
    { file: "/se/lib/hit/v4-3.mp3", title: "hit ミックス 3（13 素材・うちニコニ・コモンズ 7・10.0s）", seconds: 10.0 },
    { file: "/se/lib/hit/v4-4.mp3", title: "hit ミックス 4（13 素材・うちニコニ・コモンズ 8・10.0s）", seconds: 10.0 },
    { file: "/se/lib/hit/v4-5.mp3", title: "hit ミックス 5（13 素材・うちニコニ・コモンズ 7・9.8s）", seconds: 9.8 },
  ],
  "lite-hit": [
    { file: "/se/lib/lite-hit/v5-1.mp3", title: "lite-hit 控えめ 1（正解音１・1.2s）", seconds: 1.2 },
    { file: "/se/lib/lite-hit/v5-2.mp3", title: "lite-hit 控えめ 2（【効果音】ピンポン（クイズ正解音）・1.1s）", seconds: 1.11 },
    { file: "/se/lib/lite-hit/v5-3.mp3", title: "lite-hit 控えめ 3（correct・0.3s）", seconds: 0.32 },
    { file: "/se/lib/lite-hit/v5-4.mp3", title: "lite-hit 控えめ 4（アクセント効果音、キラン・0.8s）", seconds: 0.84 },
    { file: "/se/lib/lite-hit/v5-5.mp3", title: "lite-hit 控えめ 5（【効果音】キュピーン♪・1.0s）", seconds: 1.01 },
  ],
  "lite-coin": [
    { file: "/se/lib/lite-coin/v5-1.mp3", title: "lite-coin 控えめ 1（コイントス（コインを弾く）音２・1.0s）", seconds: 1.0 },
    { file: "/se/lib/lite-coin/v5-2.mp3", title: "lite-coin 控えめ 2（Clinking coins・0.7s）", seconds: 0.74 },
    { file: "/se/lib/lite-coin/v5-3.mp3", title: "lite-coin 控えめ 3（Fluttering coin・0.5s）", seconds: 0.51 },
  ],
  "lite-sparkle": [
    { file: "/se/lib/lite-sparkle/v5-1.mp3", title: "lite-sparkle 控えめ 1（アクセント効果音、キラン・0.8s）", seconds: 0.84 },
    { file: "/se/lib/lite-sparkle/v5-2.mp3", title: "lite-sparkle 控えめ 2（【効果音】キュピーン♪・1.0s）", seconds: 1.0 },
    { file: "/se/lib/lite-sparkle/v5-3.mp3", title: "lite-sparkle 控えめ 3（Fairy magic sparkle・0.8s）", seconds: 0.77 },
  ],
  "lite-heart": [
    { file: "/se/lib/lite-heart/v5-1.mp3", title: "lite-heart 控えめ 1（ちゅっちゅ音・0.3s）", seconds: 0.33 },
    { file: "/se/lib/lite-heart/v5-2.mp3", title: "lite-heart 控えめ 2（Cartoon Kiss_cjohnstone.・0.5s）", seconds: 0.5 },
    { file: "/se/lib/lite-heart/v5-3.mp3", title: "lite-heart 控えめ 3（perfect_kiss.mp3・0.6s）", seconds: 0.61 },
  ],
  "lite-balloon": [
    { file: "/se/lib/lite-balloon/v5-1.mp3", title: "lite-balloon 控えめ 1（風船ガムが破裂した様な軽い感じの爆発音・0.2s）", seconds: 0.18 },
    { file: "/se/lib/lite-balloon/v5-2.mp3", title: "lite-balloon 控えめ 2（【効果音】ゴムパッチン　・0.2s）", seconds: 0.18 },
    { file: "/se/lib/lite-balloon/v5-3.mp3", title: "lite-balloon 控えめ 3（Game balloon or bubble p・1.0s）", seconds: 1.0 },
  ],
  "lite-cat": [
    { file: "/se/lib/lite-cat/v5-1.mp3", title: "lite-cat 控えめ 1（【効果音】 猫の鳴き声01 にゃ～ん・0.8s）", seconds: 0.81 },
    { file: "/se/lib/lite-cat/v5-2.mp3", title: "lite-cat 控えめ 2（【猫】かまってほしげな鳴き声4・1.0s）", seconds: 0.95 },
    { file: "/se/lib/lite-cat/v5-3.mp3", title: "lite-cat 控えめ 3（【猫】かまってほしげな鳴き声3・1.0s）", seconds: 1.0 },
  ],
  "lite-dog": [
    { file: "/se/lib/lite-dog/v5-1.mp3", title: "lite-dog 控えめ 1（【効果音】 犬の鳴き声02 （中高音わん）・0.3s）", seconds: 0.31 },
    { file: "/se/lib/lite-dog/v5-2.mp3", title: "lite-dog 控えめ 2（【効果音】 犬の鳴き声03 （低めわん）・0.4s）", seconds: 0.44 },
    { file: "/se/lib/lite-dog/v5-3.mp3", title: "lite-dog 控えめ 3（15-PerritoGuauTierno.wav・0.4s）", seconds: 0.43 },
    { file: "/se/lib/lite-dog/v5-4.mp3", title: "lite-dog 控えめ 4（Single Dog Bark・0.2s）", seconds: 0.19 },
  ],
  "lite-pig": [
    { file: "/se/lib/lite-pig/v5-1.mp3", title: "lite-pig 控えめ 1（Pig Oink・0.7s）", seconds: 0.74 },
    { file: "/se/lib/lite-pig/v5-2.mp3", title: "lite-pig 控えめ 2（Pig Sound・0.6s）", seconds: 0.65 },
    { file: "/se/lib/lite-pig/v5-3.mp3", title: "lite-pig 控えめ 3（Pig Grunt・0.4s）", seconds: 0.38 },
  ],
  "lite-bird": [
    { file: "/se/lib/lite-bird/v5-1.mp3", title: "lite-bird 控えめ 1（ひよこっぽい・1.0s）", seconds: 1.0 },
    { file: "/se/lib/lite-bird/v5-2.mp3", title: "lite-bird 控えめ 2（Double little bird chirp・0.6s）", seconds: 0.59 },
    { file: "/se/lib/lite-bird/v5-3.mp3", title: "lite-bird 控えめ 3（Little bird calling chir・1.0s）", seconds: 1.0 },
  ],
  "lite-cow": [
    { file: "/se/lib/lite-cow/v5-1.mp3", title: "lite-cow 控えめ 1（Cow single moo・1.0s）", seconds: 1.0 },
    { file: "/se/lib/lite-cow/v5-2.mp3", title: "lite-cow 控えめ 2（Cow dry moo・1.0s）", seconds: 1.0 },
    { file: "/se/lib/lite-cow/v5-3.mp3", title: "lite-cow 控えめ 3（牛舎の牛のモー・1.0s）", seconds: 1.0 },
  ],
  "lite-cute": [
    { file: "/se/lib/lite-cute/v5-1.mp3", title: "lite-cute 控えめ 1（何かがポンッと生まれるような効果音・0.4s）", seconds: 0.43 },
    { file: "/se/lib/lite-cute/v5-2.mp3", title: "lite-cute 控えめ 2（Squeaky Toy #1・0.4s）", seconds: 0.45 },
    { file: "/se/lib/lite-cute/v5-3.mp3", title: "lite-cute 控えめ 3（Long pop・0.5s）", seconds: 0.48 },
  ],
  "lite-drink": [
    { file: "/se/lib/lite-drink/v5-1.mp3", title: "lite-drink 控えめ 1（【効果音】 飲食：グラスがぶつかった時の音01（・0.4s）", seconds: 0.42 },
    { file: "/se/lib/lite-drink/v5-2.mp3", title: "lite-drink 控えめ 2（コップを置く２・0.4s）", seconds: 0.42 },
    { file: "/se/lib/lite-drink/v5-3.mp3", title: "lite-drink 控えめ 3（Champagne Cork・0.5s）", seconds: 0.52 },
  ],
  "lite-food": [
    { file: "/se/lib/lite-food/v5-1.mp3", title: "lite-food 控えめ 1（食べる音・0.3s）", seconds: 0.35 },
    { file: "/se/lib/lite-food/v5-2.mp3", title: "lite-food 控えめ 2（carrotnom.wav・0.6s）", seconds: 0.58 },
    { file: "/se/lib/lite-food/v5-3.mp3", title: "lite-food 控えめ 3（Bite (Apple)・0.7s）", seconds: 0.69 },
  ],
  "lite-bell": [
    { file: "/se/lib/lite-bell/v5-1.mp3", title: "lite-bell 控えめ 1（correct・0.3s）", seconds: 0.32 },
    { file: "/se/lib/lite-bell/v5-2.mp3", title: "lite-bell 控えめ 2（Relaxing bell chime・1.0s）", seconds: 1.0 },
    { file: "/se/lib/lite-bell/v5-3.mp3", title: "lite-bell 控えめ 3（Page forward single chim・0.9s）", seconds: 0.9 },
  ],
  "lite-christmas": [
    { file: "/se/lib/lite-christmas/v5-1.mp3", title: "lite-christmas 控えめ 1（【効果音・素材】シャン……【鈴】・1.0s）", seconds: 1.0 },
    { file: "/se/lib/lite-christmas/v5-2.mp3", title: "lite-christmas 控えめ 2（Sleigh bells hit・0.9s）", seconds: 0.88 },
    { file: "/se/lib/lite-christmas/v5-3.mp3", title: "lite-christmas 控えめ 3（Small Bell #2・0.7s）", seconds: 0.74 },
  ],
  "lite-sea": [
    { file: "/se/lib/lite-sea/v5-1.mp3", title: "lite-sea 控えめ 1（Water bubble・0.2s）", seconds: 0.21 },
    { file: "/se/lib/lite-sea/v5-2.mp3", title: "lite-sea 控えめ 2（Liquid bubble・0.5s）", seconds: 0.48 },
    { file: "/se/lib/lite-sea/v5-3.mp3", title: "lite-sea 控えめ 3（水に落ちる・1.0s）", seconds: 1.0 },
  ],
  "lite-flower": [
    { file: "/se/lib/lite-flower/v5-1.mp3", title: "lite-flower 控えめ 1（キラリン、ベルのかわいい効果音・1.0s）", seconds: 1.0 },
    { file: "/se/lib/lite-flower/v5-2.mp3", title: "lite-flower 控えめ 2（生のウインドチャイムのシャラララーンの音。キラキ・1.0s）", seconds: 1.0 },
    { file: "/se/lib/lite-flower/v5-3.mp3", title: "lite-flower 控えめ 3（Mystical Wind Chimes Tra・1.0s）", seconds: 1.0 },
  ],
  "lite-pop": [
    { file: "/se/lib/lite-pop/v5-1.mp3", title: "lite-pop 控えめ 1（【SE】決定音３・0.5s）", seconds: 0.55 },
    { file: "/se/lib/lite-pop/v5-2.mp3", title: "lite-pop 控えめ 2（Bubble pop up alert noti・0.4s）", seconds: 0.38 },
    { file: "/se/lib/lite-pop/v5-3.mp3", title: "lite-pop 控えめ 3（「スポッ」抜ける音・ポップ音・0.2s）", seconds: 0.24 },
    { file: "/se/lib/lite-pop/v5-4.mp3", title: "lite-pop 控えめ 4（Dry pop up notification ・0.3s）", seconds: 0.3 },
  ],
  "lite-dice": [
    { file: "/se/lib/lite-dice/v5-1.mp3", title: "lite-dice 控えめ 1（ダイス音・2（2D10）・1.2s）", seconds: 1.2 },
    { file: "/se/lib/lite-dice/v5-2.mp3", title: "lite-dice 控えめ 2（ダイス音・1（1D10）・1.2s）", seconds: 1.2 },
    { file: "/se/lib/lite-dice/v5-3.mp3", title: "lite-dice 控えめ 3（ダイスロール音 2d6・1.2s）", seconds: 1.2 },
  ],
};

export const AUTO_LIBRARY_FILE_COUNT = 346;

export const AUTO_LIBRARY_NICOMMONS_CREDITS: readonly AutoLibraryCredit[] = [
  { id: "nc1281", title: "【効果音】ピンポン（クイズ正解音）", author: "suica", notice: "" },
  { id: "nc1485", title: "C58型蒸気機関車警笛（秩父鉄道）", author: "八ミツ", notice: "" },
  { id: "nc9824", title: "ピキーン", author: "beanjam", notice: "" },
  { id: "nc17706", title: "【猫】かまってほしげな鳴き声2", author: "おれえもん", notice: "" },
  { id: "nc17974", title: "ちゅっちゅ音", author: "woystr", notice: "" },
  { id: "nc18265", title: "【猫】かまってほしげな鳴き声3", author: "おれえもん", notice: "" },
  { id: "nc18954", title: "チャイム（ぴんぽんぱんぽん）", author: "アイス芋P", notice: "作者: アイス芋P https://commons.nicovideo.jp/material/nc18954" },
  { id: "nc19814", title: "【効果音】船の汽笛（っぽい音）", author: "でぃめとろ丼", notice: "" },
  { id: "nc20014", title: "電撃から爆発へ", author: "ハンムラビ法典", notice: "" },
  { id: "nc20549", title: "チャイム（ぴんぽんぱんぽん）下降音ver.", author: "アイス芋P", notice: "作者: アイス芋P https://commons.nicovideo.jp/material/nc20549" },
  { id: "nc23432", title: "【SE】決定音１", author: "退会済みのユーザー", notice: "" },
  { id: "nc23434", title: "【SE】決定音３", author: "退会済みのユーザー", notice: "" },
  { id: "nc25723", title: "SLの汽笛", author: "W.Knight", notice: "" },
  { id: "nc34608", title: "風船ガムが破裂した様な軽い感じの爆発音", author: "クルツ君", notice: "" },
  { id: "nc36141", title: "ダイスロール音 2d6", author: "オットー・ジャーク", notice: "" },
  { id: "nc40734", title: "爆発音（強）", author: "佐藤なにがし", notice: "" },
  { id: "nc42339", title: "ダイス音・1（1D10）", author: "ウッドダイスP", notice: "" },
  { id: "nc42340", title: "ダイス音・2（2D10）", author: "ウッドダイスP", notice: "" },
  { id: "nc43228", title: "【猫】かまってほしげな鳴き声4", author: "おれえもん", notice: "" },
  { id: "nc44013", title: "ピンポーン（ドアチャイム）", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc44182", title: "ボリボリ食べる", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc44241", title: "ラーメンを啜る１", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc44346", title: "ベル（チャイム）の音", author: "（仮）", notice: "" },
  { id: "nc45144", title: "猫がニャーン", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc45215", title: "キス１", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc45628", title: "素振り１", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc45629", title: "素振り２", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc45710", title: "火・炎１", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc45711", title: "火・炎２", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc45833", title: "正解音１", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc45835", title: "正解音３", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc45841", title: "ワープ１", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc45875", title: "ドラゴンブレス", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc45952", title: "回復音", author: "hiroyuki", notice: "" },
  { id: "nc46070", title: "コップを置く２", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc46662", title: "拍手（短め）", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc46696", title: "打ち上げ花火２", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc46697", title: "打ち上げ花火３", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc46807", title: "ピコン！３・ファミコン風効果音", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc46808", title: "ピコン！４・ファミコン風効果音", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc46809", title: "ピコン！ファミコン風効果音", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc46958", title: "レーザービーム", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc46976", title: "ボン！小爆発", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc46981", title: "発射1", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc48126", title: " ダイス1D6", author: "袖時雨うさぎ", notice: "" },
  { id: "nc49461", title: "コイン音", author: "赤バンダナ犬", notice: "" },
  { id: "nc61912", title: "稲妻（近距離）１", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc66541", title: "効果音・喫茶店のドアを開ける音（チャイム）", author: "ゆないキズト", notice: "" },
  { id: "nc66997", title: "太いビーム音", author: "piruco", notice: "" },
  { id: "nc68236", title: "【効果音】 お金の音03 （硬貨）", author: "ごじたん", notice: "" },
  { id: "nc68317", title: "【効果音】 人々の歓声・拍手01 （登場を待ち侘びたVer.）", author: "ごじたん", notice: "" },
  { id: "nc68330", title: "【効果音】 お金の音04 （硬貨）", author: "ごじたん", notice: "" },
  { id: "nc69990", title: "正解音（ピンポーン）", author: "もっぴーさうんど", notice: "" },
  { id: "nc79199", title: "キラキラ", author: "kenapo", notice: "" },
  { id: "nc79229", title: "ルーレットマシン", author: "kenapo", notice: "" },
  { id: "nc79231", title: "黄色い歓声", author: "kenapo", notice: "" },
  { id: "nc79258", title: "時計の鐘", author: "kenapo", notice: "" },
  { id: "nc85805", title: "【喫茶店風】　チャイム（ベル）　【SE】", author: "寿ゆきや", notice: "" },
  { id: "nc86818", title: "ファンファーレ", author: "ガン★ガゼ", notice: "" },
  { id: "nc88789", title: "風船破裂１", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc88790", title: "風船破裂（多い）２", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc95762", title: "ファンファーレ素材", author: "霧四面体", notice: "" },
  { id: "nc96405", title: "ピューン（発射音）", author: "退会済みのユーザー", notice: "" },
  { id: "nc97105", title: "鉄風鈴", author: "退会済みのユーザー", notice: "" },
  { id: "nc99094", title: "ひよこっぽい", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc99106", title: "小破裂（クラッカー）", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc99107", title: "クラッカー連続", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc99122", title: "炎４", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc101271", title: "ワンワンワン！a", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc102411", title: "【効果音】 飲食：グラスがぶつかった時の音01（乾杯）", author: "ごじたん", notice: "" },
  { id: "nc104542", title: "20101223_熊本港で子牛の鳴声_20110124-01.wav", author: "kdmsz", notice: "" },
  { id: "nc104890", title: "【効果音】 犬の鳴き声02 （中高音わん）", author: "ごじたん", notice: "" },
  { id: "nc105292", title: "【効果音】 鳥：ウグイスの鳴き声01", author: "ごじたん", notice: "" },
  { id: "nc105400", title: "【効果音】 猫の鳴き声01 にゃ～ん", author: "ごじたん", notice: "" },
  { id: "nc105645", title: "【効果音】 犬の鳴き声03 （低めわん）", author: "ごじたん", notice: "" },
  { id: "nc110454", title: "鶏(にわとり)の鳴き声", author: "Beardman", notice: "" },
  { id: "nc119146", title: "【効果音】 犬の鳴き声06 （ﾜﾝﾜﾝﾜﾝﾜﾝﾜﾝ!!）", author: "ごじたん", notice: "" },
  { id: "nc120904", title: "ビームライフルみたいな射撃音", author: "Chisato Kimura", notice: "" },
  { id: "nc121145", title: "雷の音（閃光を伴った雷鳴）", author: "Chisato Kimura", notice: "" },
  { id: "nc127220", title: "パンチ、打撃音、つっこみを入れる", author: "Chisato Kimura", notice: "" },
  { id: "nc129326", title: "ピロピロピロピロ", author: "Picatrix(ぴかとりくす)", notice: "" },
  { id: "nc133211", title: "ゾウの鳴き声", author: "ゲスト", notice: "" },
  { id: "nc134337", title: "キラリン、ベルのかわいい効果音", author: "UO", notice: "" },
  { id: "nc134346", title: "生のウインドチャイムのシャラララーンの音。キラキラ音。", author: "UO", notice: "" },
  { id: "nc136090", title: "鳥が飛び立つ音", author: "ゲスト", notice: "" },
  { id: "nc137849", title: "ファンファーレ [8bitFanfare186WL]　8bit　ピコピコ音　クリア", author: "スタジオランス", notice: "" },
  { id: "nc138711", title: "【効果音】パフパフラッパ_1回パフッ", author: "もっぴーさうんど", notice: "" },
  { id: "nc138714", title: "【効果音】パフパフラッパ_連続パフパフパフ", author: "もっぴーさうんど", notice: "" },
  { id: "nc141226", title: "花火の音【単発】", author: "ゲスト", notice: "" },
  { id: "nc142440", title: "古い教会の鐘", author: "ゲスト", notice: "" },
  { id: "nc146227", title: "コイントス（コインを弾く）音２", author: "ゲスト", notice: "" },
  { id: "nc147272", title: "イヨー　掛け声　効果音", author: "ヘラクレスン", notice: "" },
  { id: "nc147274", title: "おーー　歓声　効果音", author: "ヘラクレスン", notice: "" },
  { id: "nc147300", title: "歓声２　効果音", author: "ヘラクレスン", notice: "" },
  { id: "nc147376", title: "炎　効果音", author: "ヘラクレスン", notice: "" },
  { id: "nc148571", title: "コインが床に落ちる音", author: "ゲスト", notice: "" },
  { id: "nc149228", title: "何かがポンッと生まれるような効果音", author: "チョコミント", notice: "" },
  { id: "nc152052", title: "【効果音】 落雷02 （驚き/衝撃/ショック/動揺）", author: "ごじたん", notice: "" },
  { id: "nc153014", title: "食べる音", author: "ゲスト", notice: "" },
  { id: "nc154229", title: "【効果音】馬の鳴き声", author: "imorin", notice: "" },
  { id: "nc158816", title: "効果音　炎", author: "牙突", notice: "" },
  { id: "nc160462", title: "アクセント効果音、キラン", author: "UO", notice: "" },
  { id: "nc163959", title: "大太鼓を「ドドーン……！」と2回叩く", author: "Chisato Kimura", notice: "" },
  { id: "nc165372", title: "「スポッ」抜ける音・ポップ音", author: "Chisato Kimura", notice: "" },
  { id: "nc165444", title: "水に落ちる", author: "じんどっしゅ", notice: "" },
  { id: "nc168168", title: "【効果音・素材】シャン……【鈴】", author: "E-Note", notice: "" },
  { id: "nc169011", title: "【効果音】テッテレー♪", author: "tces", notice: "" },
  { id: "nc169286", title: "【効果音】テッテレー♪２", author: "tces", notice: "" },
  { id: "nc169415", title: "【効果音】キュピーン♪", author: "tces", notice: "" },
  { id: "nc169913", title: "【リアル赤ちゃんシリーズ】キャッキャッ(笑い声)", author: "こーち", notice: "" },
  { id: "nc170763", title: "【効果音】テッテレー♪３", author: "tces", notice: "" },
  { id: "nc172144", title: "【効果音】テッテレー♪４", author: "tces", notice: "" },
  { id: "nc174799", title: "ファンファーレ　レトロ　ゲームクリア　達成　勝利", author: "スタジオランス", notice: "" },
  { id: "nc179668", title: "魔法攻撃_光", author: "春秋冬（ナツナシ）", notice: "" },
  { id: "nc180463", title: "【効果音】場面転換２３", author: "tces", notice: "" },
  { id: "nc184676", title: "クラクション１", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc184680", title: "クラクション５（長）", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc186196", title: "クラッカー", author: "たのし見", notice: "" },
  { id: "nc186892", title: "牛舎の牛のモー", author: "無料効果音で遊ぼう！（小森平）", notice: "効果音：小森平「無料効果音で遊ぼう！」https://taira-komori.net/" },
  { id: "nc190938", title: "【効果音】ビーム音", author: "yonaka", notice: "" },
  { id: "nc194717", title: "【ジングル】リコーダーと木琴の可愛いジングル", author: "yonaka", notice: "" },
  { id: "nc197182", title: "ファンファーレ　レベルアップ　ゲームクリア　勝利　正解　達成", author: "スタジオランス", notice: "" },
  { id: "nc197183", title: "ファンファーレ　レベルアップ　ゲームクリア　勝利　正解　成功", author: "スタジオランス", notice: "" },
  { id: "nc198570", title: "【ジングル】ハープと鉄琴の可愛いジングル", author: "yonaka", notice: "" },
  { id: "nc202989", title: "【フリーSE】ピーン↑ポーンパーンポーン01♫【フリー素材あそび】", author: "フリー素材あそび", notice: "" },
  { id: "nc204083", title: "ハープの音、シャララン、変身、登場、魔法、キラキラ", author: "UO", notice: "" },
  { id: "nc207950", title: "イーッヒッヒッヒな笑い", author: "じんどっしゅ", notice: "" },
  { id: "nc210193", title: "【動画制作用SE】短い拍手喝采 サウンドロゴ、ジングル 05", author: "UO", notice: "" },
  { id: "nc211016", title: "【効果音】ゴムパッチン　", author: "やきう　丸いなんｊ民描いた人", notice: "" },
  { id: "nc212874", title: "幕間音楽3【Rave,フィーバータイム】", author: "NAOSHI＊", notice: "" },
  { id: "nc215042", title: "雷属性の攻撃音", author: "Justina", notice: "" },
  { id: "nc229075", title: "ルーレットの音", author: "さざめき通り", notice: "" },
  { id: "nc248305", title: "勝利BGM その１", author: "うぃむのいん", notice: "" },
  { id: "nc257697", title: "【効果音】衝撃音・地響き", author: "yonaka", notice: "" },
  { id: "nc257698", title: "【効果音】衝撃音・地響き02", author: "yonaka", notice: "" },
  { id: "nc261433", title: "未来の大型武器を撃つ音", author: "牙突", notice: "" },
  { id: "nc268083", title: "パパーン！", author: "morichan", notice: "" },
  { id: "nc268306", title: "ファンファーレっぽいジングル・A", author: "R.M.", notice: "" },
  { id: "nc272529", title: "当たりの効果音", author: "うぃむのいん", notice: "" },
  { id: "nc274317", title: "リバースシンバル", author: "青きりん", notice: "" },
  { id: "nc280643", title: "落雷｜効果音", author: "よんまるよんD", notice: "" },
  { id: "nc292187", title: "当たりの効果音 その2", author: "うぃむのいん", notice: "" },
  { id: "nc301091", title: "「リアル」牛鳴き声", author: "音の輪[リアル効果音制作部]", notice: "" },
  { id: "nc356453", title: "当たりの効果音 その3", author: "うぃむのいん", notice: "" },
  { id: "nc376119", title: "フォッ / 素早い動きの効果音 / Moment_05", author: "Yumit St.", notice: "" },
  { id: "nc383982", title: "【効果音】ピューン・飛んでいく音・コミカル", author: "たつろー・Tスタ", notice: "" },
  { id: "nc460504", title: "インパクト・スロット・パチスロ・その２", author: "たつろー・Tスタ", notice: "" },
  { id: "nc460505", title: "インパクト・スロット・パチスロ・その３", author: "たつろー・Tスタ", notice: "" },
  { id: "nc460510", title: "インパクト・スロット・パチスロ・その８", author: "たつろー・Tスタ", notice: "" },
  { id: "nc460512", title: "インパクト・スロット・パチスロ・その９", author: "たつろー・Tスタ", notice: "" },
  { id: "nc460513", title: "インパクト・スロット・パチスロ・その１０", author: "たつろー・Tスタ", notice: "" },
];
