// 自動生成: scratchpad/gen_auto_library_data.py（元: public/se/lib/manifest.json）。手で編集しない。
// 生成 2026-09-29T10:34:44Z・出典 mixkit: Mixkit Sound Effects Free License（商用可・帰属不要・音源単体の再配布は不可）https://mixkit.co/license/#sfxFree / freesound: Creative Commons 0（CC0・帰属不要）検索フィルタで絞り込み https://freesound.org/ / maou: 魔王魂 素材利用規約（商用可・改変可・可能な限り「効果音：魔王魂」の著作表記）https://maou.audio/rule/
export interface AutoLibraryFile {
  /** サイト相対 URL（public/se/lib/…） */
  file: string;
  /** 元のタイトル（英語・ラベル表示用） */
  title: string;
  seconds: number;
}

export const AUTO_LIBRARY: Readonly<Record<string, readonly AutoLibraryFile[]>> = {
  "fireworks": [
    { file: "/se/lib/fireworks/fs117616.mp3", title: "fireworks exploding 1.wav", seconds: 5.49 },
    { file: "/se/lib/fireworks/fs88532.mp3", title: "Woosh_northern87", seconds: 1.39 },
    { file: "/se/lib/fireworks/mk2993.mp3", title: "Firework rockets exploding in the sky", seconds: 2.27 },
    { file: "/se/lib/fireworks/mk1689.mp3", title: "Multiple fireworks explosions", seconds: 3.27 },
    { file: "/se/lib/fireworks/mk2994.mp3", title: "Clear firework explosions", seconds: 2.28 },
  ],
  "fanfare": [
    { file: "/se/lib/fanfare/mk2285.mp3", title: "Orchestra triumphant trumpets", seconds: 4.53 },
    { file: "/se/lib/fanfare/fs456966.mp3", title: "Success Fanfare Trumpets.mp3", seconds: 4.44 },
    { file: "/se/lib/fanfare/fs397355.mp3", title: "Tada Fanfare A", seconds: 1.72 },
    { file: "/se/lib/fanfare/fs256128.mp3", title: "TaDa!.aif", seconds: 5.58 },
    { file: "/se/lib/fanfare/mk2292.mp3", title: "Orchestra trumpets ending", seconds: 4.0 },
  ],
  "win": [
    { file: "/se/lib/win/fs253177.mp3", title: "Retro \"Accomplished\" SFX", seconds: 0.34 },
    { file: "/se/lib/win/fs162473.mp3", title: "successful.mp3", seconds: 3.16 },
    { file: "/se/lib/win/fs368651.mp3", title: "Game Powerup", seconds: 1.09 },
    { file: "/se/lib/win/mk600.mp3", title: "Achievement bell", seconds: 2.4 },
    { file: "/se/lib/win/mk269.mp3", title: "Quick win video game notification", seconds: 1.92 },
  ],
  "jackpot": [
    { file: "/se/lib/jackpot/mk1999.mp3", title: "Gold coin prize", seconds: 1.96 },
    { file: "/se/lib/jackpot/fs656643.mp3", title: "Game Reward", seconds: 5.0 },
    { file: "/se/lib/jackpot/fs361346.mp3", title: "slot machine payout.wav", seconds: 3.82 },
    { file: "/se/lib/jackpot/fs367462.mp3", title: "MENEZ_Corentin_2016_2017_Slots machine.wav", seconds: 6.01 },
    { file: "/se/lib/jackpot/mk1993.mp3", title: "Clinking coins", seconds: 1.02 },
  ],
  "coin": [
    { file: "/se/lib/coin/fs17502.mp3", title: "Coin dropping.wav", seconds: 2.03 },
    { file: "/se/lib/coin/mk1993.mp3", title: "Clinking coins", seconds: 1.02 },
    { file: "/se/lib/coin/mk1999.mp3", title: "Gold coin prize", seconds: 1.96 },
    { file: "/se/lib/coin/fs324760.mp3", title: "coin drop on concrete", seconds: 1.53 },
    { file: "/se/lib/coin/fs121990.mp3", title: "coinBag.wav", seconds: 0.51 },
  ],
  "cheer": [
    { file: "/se/lib/cheer/mk515.mp3", title: "Girls crowd cheer, scream, and applause", seconds: 6.06 },
    { file: "/se/lib/cheer/fs277022.mp3", title: "Applause 1.WAV", seconds: 6.56 },
    { file: "/se/lib/cheer/fs139972.mp3", title: "Crowd.Yay.Applause.25ppl.Short.wav", seconds: 7.42 },
    { file: "/se/lib/cheer/fs333404.mp3", title: "Cheer 2.wav", seconds: 4.08 },
    { file: "/se/lib/cheer/mk476.mp3", title: "Conference audience clapping strongly", seconds: 8.0 },
  ],
  "sparkle": [
    { file: "/se/lib/sparkle/mk871.mp3", title: "Fairy magic sparkle", seconds: 1.15 },
    { file: "/se/lib/sparkle/mk866.mp3", title: "Fairy arcade sparkle", seconds: 1.5 },
    { file: "/se/lib/sparkle/mk869.mp3", title: "Fairy sparkle whoosh", seconds: 3.79 },
    { file: "/se/lib/sparkle/fs562292.mp3", title: "Heal - Rpg", seconds: 1.23 },
    { file: "/se/lib/sparkle/fs639429.mp3", title: "Crystal Twinkle", seconds: 3.85 },
  ],
  "magic": [
    { file: "/se/lib/magic/fs264981.mp3", title: "SFX Magic", seconds: 1.95 },
    { file: "/se/lib/magic/fs349201.mp3", title: "Magic mallet.wav", seconds: 4.67 },
    { file: "/se/lib/magic/fs351408.mp3", title: "GLEAM-GLOW-SFX-CHIME.wav", seconds: 3.99 },
    { file: "/se/lib/magic/mk3062.mp3", title: "Magic wand sparkle", seconds: 2.5 },
    { file: "/se/lib/magic/mk2999.mp3", title: "Magic bubbles spell", seconds: 1.67 },
  ],
  "heart": [
    { file: "/se/lib/heart/fs536335.mp3", title: "Cartoon Kiss_cjohnstone.wav", seconds: 1.4 },
    { file: "/se/lib/heart/fs179303.mp3", title: "perfect_kiss.mp3", seconds: 0.72 },
    { file: "/se/lib/heart/mk2192.mp3", title: "Little cute kiss", seconds: 1.08 },
    { file: "/se/lib/heart/fs430594.mp3", title: "Kissing", seconds: 0.25 },
    { file: "/se/lib/heart/mk2194.mp3", title: "Cartoon friendly kiss", seconds: 1.03 },
  ],
  "balloon": [
    { file: "/se/lib/balloon/fs431532.mp3", title: "Popping", seconds: 0.45 },
    { file: "/se/lib/balloon/mk3069.mp3", title: "Game balloon or bubble pop", seconds: 1.18 },
    { file: "/se/lib/balloon/fs188381.mp3", title: "3 Popping Pops", seconds: 2.95 },
    { file: "/se/lib/balloon/fs82121.mp3", title: "Balloon-Burst-07.wav", seconds: 0.89 },
    { file: "/se/lib/balloon/mk3073.mp3", title: "Inflating a ballon", seconds: 3.82 },
  ],
  "cat": [
    { file: "/se/lib/cat/fs110011.mp3", title: "cat meow", seconds: 1.54 },
    { file: "/se/lib/cat/fs333916.mp3", title: "Cat Meowing", seconds: 1.28 },
    { file: "/se/lib/cat/fs412017.mp3", title: "cat meow short", seconds: 1.67 },
    { file: "/se/lib/cat/mk93.mp3", title: "Sweet kitty meow", seconds: 0.87 },
    { file: "/se/lib/cat/mk92.mp3", title: "Cartoon kitty begging meow", seconds: 2.5 },
  ],
  "dog": [
    { file: "/se/lib/dog/fs163459.mp3", title: "LBS_FX DOG Small Alert Bark001.wav", seconds: 1.7 },
    { file: "/se/lib/dog/fs386766.mp3", title: "Dog_Barking.wav", seconds: 2.59 },
    { file: "/se/lib/dog/mk1.mp3", title: "Dog barking twice", seconds: 1.62 },
    { file: "/se/lib/dog/mk51.mp3", title: "Annoyed big dog barking", seconds: 2.97 },
    { file: "/se/lib/dog/fs231762.mp3", title: "FX_Dog Barking.wav", seconds: 1.56 },
  ],
  "pig": [
    { file: "/se/lib/pig/fs442906.mp3", title: "Pig Oink", seconds: 0.74 },
    { file: "/se/lib/pig/fs233151.mp3", title: "Pig - Scream 5 - 96kHz.wav", seconds: 1.94 },
    { file: "/se/lib/pig/fs233183.mp3", title: "Pig - Multiple Snorts 2 (2 pigs) - 96kHz.wav", seconds: 1.57 },
    { file: "/se/lib/pig/fs442907.mp3", title: "Pig Grunt", seconds: 0.37 },
    { file: "/se/lib/pig/fs233182.mp3", title: "Pig - Multiple Snorts 3 (2 pigs) - 96kHz.wav", seconds: 1.44 },
  ],
  "elephant": [
    { file: "/se/lib/elephant/fs527845.mp3", title: "Elephant Trumpets Growls.flac", seconds: 1.96 },
    { file: "/se/lib/elephant/fs139052.mp3", title: "Elephant scream.wav", seconds: 1.5 },
    { file: "/se/lib/elephant/fs72464.mp3", title: "elephant1.wav", seconds: 3.41 },
    { file: "/se/lib/elephant/fs510490.mp3", title: "eleaudio.m4a", seconds: 2.16 },
    { file: "/se/lib/elephant/fs350421.mp3", title: "Rhinoceros Trumpet Joyful", seconds: 1.34 },
  ],
  "wolf": [
    { file: "/se/lib/wolf/mk1774.mp3", title: "Cartoon wolf howling", seconds: 1.74 },
    { file: "/se/lib/wolf/mk1777.mp3", title: "Wolf creature howling roar", seconds: 4.95 },
    { file: "/se/lib/wolf/fs429109.mp3", title: "15-WolfCrying.wav", seconds: 3.28 },
    { file: "/se/lib/wolf/fs203342.mp3", title: "Howl of the night", seconds: 3.87 },
    { file: "/se/lib/wolf/fs420447.mp3", title: "Barking 4.wav", seconds: 0.58 },
  ],
  "lion": [
    { file: "/se/lib/lion/mk6.mp3", title: "Wild lion animal roar", seconds: 1.28 },
    { file: "/se/lib/lion/fs467762.mp3", title: "lion.wav", seconds: 1.38 },
    { file: "/se/lib/lion/fs567803.mp3", title: "poujade_eva_2020_2021_RoarOfLion(son2).wav", seconds: 2.0 },
    { file: "/se/lib/lion/fs571288.mp3", title: "tiger_roar.wav", seconds: 1.25 },
    { file: "/se/lib/lion/mk95.mp3", title: "Big wild lion growl", seconds: 2.31 },
  ],
  "bird": [
    { file: "/se/lib/bird/fs43382.mp3", title: "Rooster chicken calls_2.wav", seconds: 2.98 },
    { file: "/se/lib/bird/mk1772.mp3", title: "Chickens clucking short", seconds: 2.04 },
    { file: "/se/lib/bird/mk23.mp3", title: "Little bird calling chirp", seconds: 1.04 },
    { file: "/se/lib/bird/mk67.mp3", title: "Melodic songbird chirp", seconds: 1.76 },
    { file: "/se/lib/bird/fs435508.mp3", title: "Rooster Crow 1", seconds: 2.01 },
  ],
  "horse": [
    { file: "/se/lib/horse/mk85.mp3", title: "Scared horse neighing", seconds: 2.34 },
    { file: "/se/lib/horse/mk76.mp3", title: "Intense horse stallion neigh", seconds: 2.32 },
    { file: "/se/lib/horse/mk1762.mp3", title: "Stallion horse neigh", seconds: 2.9 },
    { file: "/se/lib/horse/fs269571.mp3", title: "horse neigh shortened.wav", seconds: 1.35 },
    { file: "/se/lib/horse/fs521246.mp3", title: "Horse", seconds: 1.94 },
  ],
  "cow": [
    { file: "/se/lib/cow/fs59245.mp3", title: "z-moo01.wav", seconds: 1.72 },
    { file: "/se/lib/cow/mk1751.mp3", title: "Cow moo in the barn", seconds: 2.02 },
    { file: "/se/lib/cow/mk1744.mp3", title: "Cow moo", seconds: 2.64 },
    { file: "/se/lib/cow/mk1749.mp3", title: "Cow moo indoors", seconds: 3.28 },
    { file: "/se/lib/cow/fs275154.mp3", title: "Moo.wav", seconds: 1.65 },
  ],
  "monkey": [
    { file: "/se/lib/monkey/fs325549.mp3", title: "Monkey screaming.wav", seconds: 2.99 },
    { file: "/se/lib/monkey/fs67361.mp3", title: "Affen schreit.mp3", seconds: 3.3 },
    { file: "/se/lib/monkey/fs504654.mp3", title: "Uh Oh.mp3", seconds: 1.9 },
    { file: "/se/lib/monkey/mk108.mp3", title: "Cartoon monkey mocking and giggling", seconds: 2.01 },
    { file: "/se/lib/monkey/mk107.mp3", title: "Cartoon monkey mocking laugh", seconds: 1.81 },
  ],
  "bear": [
    { file: "/se/lib/bear/fs342204.mp3", title: "Beast Snarling", seconds: 3.22 },
    { file: "/se/lib/bear/fs77637.mp3", title: "growl6.wav", seconds: 1.31 },
    { file: "/se/lib/bear/fs728102.mp3", title: "Synthetic Bear Growl 2", seconds: 2.95 },
    { file: "/se/lib/bear/fs771873.mp3", title: "Growl", seconds: 3.68 },
    { file: "/se/lib/bear/fs519598.mp3", title: "huf grizzly", seconds: 0.36 },
  ],
  "cute": [
    { file: "/se/lib/cute/fs396196.mp3", title: "Cute Anime Jumps", seconds: 1.67 },
    { file: "/se/lib/cute/fs468443.mp3", title: "Squeaky Toy #1", seconds: 0.45 },
    { file: "/se/lib/cute/mk616.mp3", title: "Cartoon toy whistle", seconds: 1.15 },
    { file: "/se/lib/cute/mk2813.mp3", title: "Funny squeaky toy hits", seconds: 1.08 },
    { file: "/se/lib/cute/mk2814.mp3", title: "Funny squeaky toy", seconds: 1.49 },
  ],
  "drink": [
    { file: "/se/lib/drink/fs392624.mp3", title: "Champagne Cork", seconds: 0.57 },
    { file: "/se/lib/drink/mk2836.mp3", title: "Glasses clinking", seconds: 1.2 },
    { file: "/se/lib/drink/mk2936.mp3", title: "Wine glass clink", seconds: 1.2 },
    { file: "/se/lib/drink/mk154.mp3", title: "A couple of glasses clink", seconds: 2.57 },
    { file: "/se/lib/drink/fs433721.mp3", title: "Cheers!.wav", seconds: 1.39 },
  ],
  "food": [
    { file: "/se/lib/food/fs106392.mp3", title: "carrotnom.wav", seconds: 0.58 },
    { file: "/se/lib/food/fs275015.mp3", title: "Bite (Apple)", seconds: 0.83 },
    { file: "/se/lib/food/fs339838.mp3", title: "mhm.mp3", seconds: 1.16 },
    { file: "/se/lib/food/mk2244.mp3", title: "Chewing something crunchy", seconds: 0.92 },
    { file: "/se/lib/food/mk1791.mp3", title: "Cooking bell ding", seconds: 1.59 },
  ],
  "party": [
    { file: "/se/lib/party/fs458398.mp3", title: "Balloon Pop / Christmas cracker / Confetti Cannon", seconds: 0.35 },
    { file: "/se/lib/party/mk530.mp3", title: "Happy party horn sound", seconds: 1.94 },
    { file: "/se/lib/party/mk526.mp3", title: "Party trumpet horn isolated", seconds: 1.14 },
    { file: "/se/lib/party/fs506982.mp3", title: "Firecracker", seconds: 4.51 },
    { file: "/se/lib/party/fs26349.mp3", title: "partypopper.flac", seconds: 0.61 },
  ],
  "bell": [
    { file: "/se/lib/bell/fs243701.mp3", title: "correct", seconds: 0.32 },
    { file: "/se/lib/bell/fs611113.mp3", title: "bell ding 1.wav", seconds: 2.51 },
    { file: "/se/lib/bell/mk3109.mp3", title: "Relaxing bell chime", seconds: 1.68 },
    { file: "/se/lib/bell/mk586.mp3", title: "Attention bell ding", seconds: 1.52 },
    { file: "/se/lib/bell/fs456161.mp3", title: "Correct.wav", seconds: 1.41 },
  ],
  "christmas": [
    { file: "/se/lib/christmas/fs369506.mp3", title: "Sleigh bells hit", seconds: 0.88 },
    { file: "/se/lib/christmas/fs452379.mp3", title: "Small Bell #2", seconds: 1.94 },
    { file: "/se/lib/christmas/fs412534.mp3", title: "Air Media - Christmas Sound.wav", seconds: 5.36 },
    { file: "/se/lib/christmas/mk584.mp3", title: "Sleigh Bells", seconds: 4.25 },
    { file: "/se/lib/christmas/mk2988.mp3", title: "Christmas reveal tones", seconds: 3.02 },
  ],
  "halloween": [
    { file: "/se/lib/halloween/fs348142.mp3", title: "Witch's Laugh.wav", seconds: 3.34 },
    { file: "/se/lib/halloween/fs223851.mp3", title: "Witch Laugh", seconds: 4.7 },
    { file: "/se/lib/halloween/fs366168.mp3", title: "Intense Jumpscare", seconds: 4.08 },
    { file: "/se/lib/halloween/fs417826.mp3", title: "Witch Cackle", seconds: 1.11 },
    { file: "/se/lib/halloween/fs646307.mp3", title: "Evil Laugh_1.wav", seconds: 3.31 },
  ],
  "sea": [
    { file: "/se/lib/sea/mk1198.mp3", title: "Sea water splash", seconds: 1.74 },
    { file: "/se/lib/sea/fs9508.mp3", title: "SPLASH.wav", seconds: 2.03 },
    { file: "/se/lib/sea/fs398032.mp3", title: "Splash", seconds: 1.33 },
    { file: "/se/lib/sea/fs442773.mp3", title: "Big Water Splash", seconds: 2.17 },
    { file: "/se/lib/sea/mk1311.mp3", title: "Water splash", seconds: 1.43 },
  ],
  "rocket": [
    { file: "/se/lib/rocket/mk1714.mp3", title: "Fast rocket whoosh", seconds: 4.46 },
    { file: "/se/lib/rocket/fs521377.mp3", title: "Rocket Launch", seconds: 1.41 },
    { file: "/se/lib/rocket/fs189327.mp3", title: "missile lock on sound", seconds: 4.96 },
    { file: "/se/lib/rocket/mk2825.mp3", title: "Sci-fi laser in space sound", seconds: 2.09 },
    { file: "/se/lib/rocket/mk3001.mp3", title: "Space shot whoosh", seconds: 1.81 },
  ],
  "explosion": [
    { file: "/se/lib/explosion/fs182429.mp3", title: "Explosion", seconds: 3.0 },
    { file: "/se/lib/explosion/fs127845.mp3", title: "Tank fire Mixed.wav", seconds: 4.45 },
    { file: "/se/lib/explosion/fs587193.mp3", title: "explosion_big_02.ogg", seconds: 3.16 },
    { file: "/se/lib/explosion/mk2782.mp3", title: "Epic impact afar explosion", seconds: 4.53 },
    { file: "/se/lib/explosion/mk1687.mp3", title: "Dramatic metal explosion impact", seconds: 4.0 },
  ],
  "casino": [
    { file: "/se/lib/casino/mk1933.mp3", title: "Arcade slot machine wheel", seconds: 3.49 },
    { file: "/se/lib/casino/fs209578.mp3", title: "Cash Register Purchase", seconds: 2.71 },
    { file: "/se/lib/casino/mk211.mp3", title: "Retro arcade casino notification", seconds: 4.12 },
    { file: "/se/lib/casino/mk1987.mp3", title: "Casino Roulette ball", seconds: 3.38 },
    { file: "/se/lib/casino/fs361346.mp3", title: "slot machine payout.wav", seconds: 3.82 },
  ],
  "music": [
    { file: "/se/lib/music/mk2321.mp3", title: "Cool guitar riff", seconds: 1.53 },
    { file: "/se/lib/music/mk2319.mp3", title: "Happy guitar chords", seconds: 1.14 },
    { file: "/se/lib/music/mk2322.mp3", title: "Short guitar riff", seconds: 1.43 },
    { file: "/se/lib/music/fs541546.mp3", title: "Flashback Sound.wav", seconds: 5.4 },
    { file: "/se/lib/music/fs167214.mp3", title: "guitar strike E.wav", seconds: 4.77 },
  ],
  "battle": [
    { file: "/se/lib/battle/mk2762.mp3", title: "Sword blade attack in medieval battle", seconds: 1.11 },
    { file: "/se/lib/battle/mk2763.mp3", title: "Sword slashes in battle", seconds: 1.16 },
    { file: "/se/lib/battle/mk2764.mp3", title: "Fast sword hit in medieval battle", seconds: 1.05 },
    { file: "/se/lib/battle/fs37596.mp3", title: "Sword.wav", seconds: 0.93 },
    { file: "/se/lib/battle/fs263595.mp3", title: "swoosh.wav", seconds: 1.83 },
  ],
  "vehicle": [
    { file: "/se/lib/vehicle/fs434878.mp3", title: "Car Honking", seconds: 0.87 },
    { file: "/se/lib/vehicle/fs461679.mp3", title: "05 Horn.wav", seconds: 3.03 },
    { file: "/se/lib/vehicle/fs170243.mp3", title: "Car Horn.wav", seconds: 0.41 },
    { file: "/se/lib/vehicle/mk1565.mp3", title: "Classic car horn", seconds: 0.51 },
    { file: "/se/lib/vehicle/mk719.mp3", title: "Car double horn", seconds: 0.86 },
  ],
  "flower": [
    { file: "/se/lib/flower/fs419594.mp3", title: "Mystical Wind Chimes Transition FX", seconds: 4.81 },
    { file: "/se/lib/flower/fs169855.mp3", title: "Wind Chime (G-003) +.wav", seconds: 3.37 },
    { file: "/se/lib/flower/fs66220.mp3", title: "bamboo1.wav", seconds: 0.31 },
    { file: "/se/lib/flower/mk3109.mp3", title: "Relaxing bell chime", seconds: 1.68 },
    { file: "/se/lib/flower/mk3108.mp3", title: "Crystal chime", seconds: 1.98 },
  ],
  "pop": [
    { file: "/se/lib/pop/mk2357.mp3", title: "Bubble pop up alert notification", seconds: 0.38 },
    { file: "/se/lib/pop/fs258193.mp3", title: "beep beep", seconds: 0.36 },
    { file: "/se/lib/pop/mk2364.mp3", title: "Hard pop click", seconds: 1.17 },
    { file: "/se/lib/pop/mk2356.mp3", title: "Dry pop up notification alert", seconds: 0.3 },
    { file: "/se/lib/pop/fs258269.mp3", title: "Mouth pop", seconds: 0.32 },
  ],
  "trophy": [
    { file: "/se/lib/trophy/fs456966.mp3", title: "Success Fanfare Trumpets.mp3", seconds: 4.44 },
    { file: "/se/lib/trophy/fs415504.mp3", title: "Tadaa.wav", seconds: 4.64 },
    { file: "/se/lib/trophy/fs269198.mp3", title: "game-win.mp3", seconds: 2.5 },
    { file: "/se/lib/trophy/mk269.mp3", title: "Quick win video game notification", seconds: 1.92 },
    { file: "/se/lib/trophy/mk2019.mp3", title: "Ethereal fairy win sound", seconds: 2.44 },
  ],
  "epic": [
    { file: "/se/lib/epic/fs177242.mp3", title: "Cinematic Impact", seconds: 7.41 },
    { file: "/se/lib/epic/fs222517.mp3", title: "Dramatic Hit", seconds: 7.04 },
    { file: "/se/lib/epic/fs427803.mp3", title: "Cinematic Hit With Horns.wav", seconds: 4.37 },
    { file: "/se/lib/epic/mk1143.mp3", title: "Cinematic whoosh deep impact", seconds: 3.92 },
    { file: "/se/lib/epic/mk2290.mp3", title: "Epic orchestra transition", seconds: 7.12 },
  ],
  "notify": [
    { file: "/se/lib/notify/fs380482.mp3", title: "Chime Notification", seconds: 0.32 },
    { file: "/se/lib/notify/mk2357.mp3", title: "Bubble pop up alert notification", seconds: 0.38 },
    { file: "/se/lib/notify/mk2356.mp3", title: "Dry pop up notification alert", seconds: 0.3 },
    { file: "/se/lib/notify/mk2320.mp3", title: "Guitar notification alert", seconds: 1.6 },
    { file: "/se/lib/notify/fs351879.mp3", title: "Computer Chimes - Notification.aif", seconds: 1.37 },
  ],
  "wow": [
    { file: "/se/lib/wow/fs162395.mp3", title: "yay.mp3", seconds: 1.83 },
    { file: "/se/lib/wow/fs353923.mp3", title: "yay.wav", seconds: 3.49 },
    { file: "/se/lib/wow/fs274510.mp3", title: "3 Men Cheering", seconds: 2.04 },
    { file: "/se/lib/wow/mk975.mp3", title: "Happy crowd cheer", seconds: 4.0 },
    { file: "/se/lib/wow/mk384.mp3", title: "Cartoon teen says thank you", seconds: 1.22 },
  ],
  "dice": [
    { file: "/se/lib/dice/fs177208.mp3", title: "Dice Rolling - Dungeon and Dragons", seconds: 3.91 },
    { file: "/se/lib/dice/fs629982.mp3", title: "Dice Rolling on Table", seconds: 1.04 },
    { file: "/se/lib/dice/fs353975.mp3", title: "rolling dice 1.wav", seconds: 0.95 },
    { file: "/se/lib/dice/fs398698.mp3", title: "Slow Pebble Tumble.wav", seconds: 0.98 },
    { file: "/se/lib/dice/fs162456.mp3", title: "Dice.mp3", seconds: 1.6 },
  ],
  "kids": [
    { file: "/se/lib/kids/fs371342.mp3", title: "D2_kidslaughing.mp3", seconds: 3.16 },
    { file: "/se/lib/kids/fs458645.mp3", title: "babygiggle.mp3", seconds: 1.81 },
    { file: "/se/lib/kids/mk2265.mp3", title: "Happy child laughing", seconds: 2.29 },
    { file: "/se/lib/kids/mk2263.mp3", title: "Child laughing happily", seconds: 0.7 },
    { file: "/se/lib/kids/mk431.mp3", title: "Kid giggle laugh", seconds: 2.28 },
  ],
  "thunder": [
    { file: "/se/lib/thunder/fs475094.mp3", title: "thunder3.ogg", seconds: 3.5 },
    { file: "/se/lib/thunder/fs195439.mp3", title: "strike 3 sec.wav", seconds: 3.68 },
    { file: "/se/lib/thunder/mk1293.mp3", title: "Fast thunder whoosh", seconds: 4.12 },
    { file: "/se/lib/thunder/mk1283.mp3", title: "Cinematic thunder", seconds: 4.92 },
    { file: "/se/lib/thunder/fs765327.mp3", title: "Thunder Strike", seconds: 5.62 },
  ],
  "fire": [
    { file: "/se/lib/fire/mk1345.mp3", title: "Short fire whoosh", seconds: 3.09 },
    { file: "/se/lib/fire/mk1328.mp3", title: "Fire swoosh burning", seconds: 3.01 },
    { file: "/se/lib/fire/mk1332.mp3", title: "Big fire spell burning", seconds: 3.9 },
    { file: "/se/lib/fire/fs171255.mp3", title: "Sliding Trailer Woosh", seconds: 1.63 },
    { file: "/se/lib/fire/fs260554.mp3", title: "Basic Fire whoosh", seconds: 3.89 },
  ],
  "laser": [
    { file: "/se/lib/laser/fs160421.mp3", title: "Electrical Shock (Zap).wav", seconds: 3.64 },
    { file: "/se/lib/laser/fs398274.mp3", title: "Electricity", seconds: 3.28 },
    { file: "/se/lib/laser/fs341612.mp3", title: "Electricity 4", seconds: 3.82 },
    { file: "/se/lib/laser/mk3201.mp3", title: "Electric charge hum", seconds: 2.38 },
    { file: "/se/lib/laser/mk1467.mp3", title: "Cinematic laser swoosh", seconds: 1.23 },
  ],
  "whoosh": [
    { file: "/se/lib/whoosh/fs60013.mp3", title: "Whoosh", seconds: 0.43 },
    { file: "/se/lib/whoosh/fs60030.mp3", title: "Swosh / Whoosh / Air Cut", seconds: 0.44 },
    { file: "/se/lib/whoosh/fs169867.mp3", title: "swoosh", seconds: 2.11 },
    { file: "/se/lib/whoosh/mk1492.mp3", title: "Cinematic whoosh fast transition", seconds: 1.28 },
    { file: "/se/lib/whoosh/mk1490.mp3", title: "Fast whoosh transition", seconds: 1.6 },
  ],
  "bulk-COOL": [
    { file: "/se/lib/bulk-COOL/fs253177.mp3", title: "Retro \"Accomplished\" SFX", seconds: 0.34 },
    { file: "/se/lib/bulk-COOL/fs368651.mp3", title: "Game Powerup", seconds: 1.09 },
    { file: "/se/lib/bulk-COOL/fs442943.mp3", title: "Level Up", seconds: 1.67 },
    { file: "/se/lib/bulk-COOL/mk600.mp3", title: "Achievement bell", seconds: 2.4 },
    { file: "/se/lib/bulk-COOL/mk269.mp3", title: "Quick win video game notification", seconds: 1.92 },
  ],
  "bulk-GREAT": [
    { file: "/se/lib/bulk-GREAT/mk515.mp3", title: "Girls crowd cheer, scream, and applause", seconds: 6.0 },
    { file: "/se/lib/bulk-GREAT/fs333404.mp3", title: "Cheer 2.wav", seconds: 4.08 },
    { file: "/se/lib/bulk-GREAT/fs415504.mp3", title: "Tadaa.wav", seconds: 4.64 },
    { file: "/se/lib/bulk-GREAT/fs463371.mp3", title: "Aplauso com Gritos.wav", seconds: 5.45 },
    { file: "/se/lib/bulk-GREAT/mk509.mp3", title: "Football team applause", seconds: 4.65 },
  ],
  "bulk-FANTASTIC": [
    { file: "/se/lib/bulk-FANTASTIC/mk2285.mp3", title: "Orchestra triumphant trumpets", seconds: 4.53 },
    { file: "/se/lib/bulk-FANTASTIC/fs456966.mp3", title: "Success Fanfare Trumpets.mp3", seconds: 4.44 },
    { file: "/se/lib/bulk-FANTASTIC/mk2292.mp3", title: "Orchestra trumpets ending", seconds: 4.0 },
    { file: "/se/lib/bulk-FANTASTIC/fs415504.mp3", title: "Tadaa.wav", seconds: 4.64 },
    { file: "/se/lib/bulk-FANTASTIC/mk2293.mp3", title: "Trumpet fanfare", seconds: 8.0 },
  ],
  "bulk-MIRACLE": [
    { file: "/se/lib/bulk-MIRACLE/mk2285.mp3", title: "Orchestra triumphant trumpets", seconds: 4.53 },
    { file: "/se/lib/bulk-MIRACLE/mk2290.mp3", title: "Epic orchestra transition", seconds: 7.12 },
    { file: "/se/lib/bulk-MIRACLE/fs336725.mp3", title: "Inception Horn Victory", seconds: 2.95 },
    { file: "/se/lib/bulk-MIRACLE/mk2294.mp3", title: "Drum bass hit", seconds: 1.53 },
    { file: "/se/lib/bulk-MIRACLE/fs812468.mp3", title: "Angelic Fanfare 2", seconds: 6.27 },
  ],
  "tier-T0": [
    { file: "/se/lib/tier-T0/fs202230.mp3", title: "Pop sound", seconds: 0.51 },
    { file: "/se/lib/tier-T0/fs19284.mp3", title: "cartoon poppyup appearances -0001.aiff", seconds: 1.48 },
    { file: "/se/lib/tier-T0/fs267952.mp3", title: "pop.wav", seconds: 1.72 },
    { file: "/se/lib/tier-T0/mk2357.mp3", title: "Bubble pop up alert notification", seconds: 0.38 },
    { file: "/se/lib/tier-T0/mk2358.mp3", title: "Long pop", seconds: 0.48 },
  ],
  "tier-T1": [
    { file: "/se/lib/tier-T1/fs380482.mp3", title: "Chime Notification", seconds: 0.32 },
    { file: "/se/lib/tier-T1/fs361564.mp3", title: "Ding Dong", seconds: 2.8 },
    { file: "/se/lib/tier-T1/fs116779.mp3", title: "Ringing bell - happy.wav", seconds: 2.64 },
    { file: "/se/lib/tier-T1/mk933.mp3", title: "Bell notification", seconds: 3.0 },
    { file: "/se/lib/tier-T1/mk937.mp3", title: "Happy bells notification", seconds: 3.0 },
  ],
  "tier-T2": [
    { file: "/se/lib/tier-T2/mk1999.mp3", title: "Gold coin prize", seconds: 1.96 },
    { file: "/se/lib/tier-T2/fs347174.mp3", title: "Coin Pickup Sound V 0.2", seconds: 0.51 },
    { file: "/se/lib/tier-T2/fs512216.mp3", title: "Coins", seconds: 0.44 },
    { file: "/se/lib/tier-T2/fs121990.mp3", title: "coinBag.wav", seconds: 0.51 },
    { file: "/se/lib/tier-T2/mk1993.mp3", title: "Clinking coins", seconds: 1.02 },
  ],
  "tier-T3": [
    { file: "/se/lib/tier-T3/fs456966.mp3", title: "Success Fanfare Trumpets.mp3", seconds: 4.44 },
    { file: "/se/lib/tier-T3/fs397355.mp3", title: "Tada Fanfare A", seconds: 1.72 },
    { file: "/se/lib/tier-T3/fs397353.mp3", title: "Tada Fanfare G", seconds: 1.69 },
    { file: "/se/lib/tier-T3/mk269.mp3", title: "Quick win video game notification", seconds: 1.92 },
    { file: "/se/lib/tier-T3/mk270.mp3", title: "Fantasy game success notification", seconds: 3.0 },
  ],
  "tier-T4": [
    { file: "/se/lib/tier-T4/mk2285.mp3", title: "Orchestra triumphant trumpets", seconds: 4.53 },
    { file: "/se/lib/tier-T4/fs456966.mp3", title: "Success Fanfare Trumpets.mp3", seconds: 4.44 },
    { file: "/se/lib/tier-T4/fs397355.mp3", title: "Tada Fanfare A", seconds: 1.72 },
    { file: "/se/lib/tier-T4/fs256128.mp3", title: "TaDa!.aif", seconds: 5.58 },
    { file: "/se/lib/tier-T4/mk2292.mp3", title: "Orchestra trumpets ending", seconds: 4.0 },
  ],
  "hit": [
    { file: "/se/lib/hit/fs243701.mp3", title: "correct", seconds: 0.32 },
    { file: "/se/lib/hit/mk1931.mp3", title: "Slot machine win alert", seconds: 3.49 },
    { file: "/se/lib/hit/fs656643.mp3", title: "Game Reward", seconds: 5.0 },
    { file: "/se/lib/hit/mk1995.mp3", title: "Slot machine win alarm", seconds: 6.0 },
    { file: "/se/lib/hit/mk1928.mp3", title: "Slot machine win", seconds: 4.97 },
  ],
};

export const AUTO_LIBRARY_FILE_COUNT = 285;
