// 自動生成: scratchpad/gen_auto_library_data.py（元: public/se/lib/manifest.json）。手で編集しない。
// 生成 2026-09-29T11:03:10Z・出典 mixkit: Mixkit Sound Effects Free License（商用可・帰属不要・音源単体の再配布は不可）https://mixkit.co/license/#sfxFree / freesound: Creative Commons 0（CC0・帰属不要）検索フィルタで絞り込み https://freesound.org/ / maou: 魔王魂 素材利用規約（商用可・改変可・可能な限り「効果音：魔王魂」の著作表記）https://maou.audio/rule/
export interface AutoLibraryFile {
  /** サイト相対 URL（public/se/lib/…） */
  file: string;
  /** 元のタイトル（英語・ラベル表示用） */
  title: string;
  seconds: number;
}

export const AUTO_LIBRARY: Readonly<Record<string, readonly AutoLibraryFile[]>> = {
  "fireworks": [
    { file: "/se/lib/fireworks/mix1.mp3", title: "fireworks ミックス 1（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/fireworks/mix2.mp3", title: "fireworks ミックス 2（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/fireworks/mix3.mp3", title: "fireworks ミックス 3（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/fireworks/mix4.mp3", title: "fireworks ミックス 4（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/fireworks/mix5.mp3", title: "fireworks ミックス 5（11 素材・9.5s）", seconds: 9.5 },
  ],
  "fanfare": [
    { file: "/se/lib/fanfare/mix1.mp3", title: "fanfare ミックス 1（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/fanfare/mix2.mp3", title: "fanfare ミックス 2（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/fanfare/mix3.mp3", title: "fanfare ミックス 3（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/fanfare/mix4.mp3", title: "fanfare ミックス 4（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/fanfare/mix5.mp3", title: "fanfare ミックス 5（11 素材・9.5s）", seconds: 9.5 },
  ],
  "win": [
    { file: "/se/lib/win/mix1.mp3", title: "win ミックス 1（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/win/mix2.mp3", title: "win ミックス 2（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/win/mix3.mp3", title: "win ミックス 3（8 素材・6.0s）", seconds: 6.04 },
    { file: "/se/lib/win/mix4.mp3", title: "win ミックス 4（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/win/mix5.mp3", title: "win ミックス 5（8 素材・6.5s）", seconds: 6.5 },
  ],
  "jackpot": [
    { file: "/se/lib/jackpot/mix1.mp3", title: "jackpot ミックス 1（12 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/jackpot/mix2.mp3", title: "jackpot ミックス 2（12 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/jackpot/mix3.mp3", title: "jackpot ミックス 3（12 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/jackpot/mix4.mp3", title: "jackpot ミックス 4（12 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/jackpot/mix5.mp3", title: "jackpot ミックス 5（12 素材・9.5s）", seconds: 9.5 },
  ],
  "coin": [
    { file: "/se/lib/coin/mix1.mp3", title: "coin ミックス 1（8 素材・6.4s）", seconds: 6.4 },
    { file: "/se/lib/coin/mix2.mp3", title: "coin ミックス 2（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/coin/mix3.mp3", title: "coin ミックス 3（8 素材・5.5s）", seconds: 5.47 },
    { file: "/se/lib/coin/mix4.mp3", title: "coin ミックス 4（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/coin/mix5.mp3", title: "coin ミックス 5（8 素材・6.5s）", seconds: 6.5 },
  ],
  "cheer": [
    { file: "/se/lib/cheer/mix1.mp3", title: "cheer ミックス 1（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/cheer/mix2.mp3", title: "cheer ミックス 2（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/cheer/mix3.mp3", title: "cheer ミックス 3（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/cheer/mix4.mp3", title: "cheer ミックス 4（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/cheer/mix5.mp3", title: "cheer ミックス 5（11 素材・9.5s）", seconds: 9.5 },
  ],
  "sparkle": [
    { file: "/se/lib/sparkle/mix1.mp3", title: "sparkle ミックス 1（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/sparkle/mix2.mp3", title: "sparkle ミックス 2（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/sparkle/mix3.mp3", title: "sparkle ミックス 3（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/sparkle/mix4.mp3", title: "sparkle ミックス 4（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/sparkle/mix5.mp3", title: "sparkle ミックス 5（8 素材・6.5s）", seconds: 6.5 },
  ],
  "magic": [
    { file: "/se/lib/magic/mix1.mp3", title: "magic ミックス 1（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/magic/mix2.mp3", title: "magic ミックス 2（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/magic/mix3.mp3", title: "magic ミックス 3（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/magic/mix4.mp3", title: "magic ミックス 4（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/magic/mix5.mp3", title: "magic ミックス 5（8 素材・6.5s）", seconds: 6.5 },
  ],
  "heart": [
    { file: "/se/lib/heart/mix1.mp3", title: "heart ミックス 1（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/heart/mix2.mp3", title: "heart ミックス 2（8 素材・6.0s）", seconds: 6.02 },
    { file: "/se/lib/heart/mix3.mp3", title: "heart ミックス 3（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/heart/mix4.mp3", title: "heart ミックス 4（8 素材・5.9s）", seconds: 5.86 },
    { file: "/se/lib/heart/mix5.mp3", title: "heart ミックス 5（8 素材・6.5s）", seconds: 6.5 },
  ],
  "balloon": [
    { file: "/se/lib/balloon/mix1.mp3", title: "balloon ミックス 1（4 素材・3.5s）", seconds: 3.5 },
    { file: "/se/lib/balloon/mix2.mp3", title: "balloon ミックス 2（4 素材・3.5s）", seconds: 3.5 },
    { file: "/se/lib/balloon/mix3.mp3", title: "balloon ミックス 3（4 素材・3.5s）", seconds: 3.5 },
    { file: "/se/lib/balloon/mix4.mp3", title: "balloon ミックス 4（4 素材・2.8s）", seconds: 2.77 },
    { file: "/se/lib/balloon/mix5.mp3", title: "balloon ミックス 5（4 素材・3.5s）", seconds: 3.5 },
  ],
  "cat": [
    { file: "/se/lib/cat/mix1.mp3", title: "cat ミックス 1（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/cat/mix2.mp3", title: "cat ミックス 2（8 素材・6.0s）", seconds: 6.02 },
    { file: "/se/lib/cat/mix3.mp3", title: "cat ミックス 3（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/cat/mix4.mp3", title: "cat ミックス 4（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/cat/mix5.mp3", title: "cat ミックス 5（8 素材・6.5s）", seconds: 6.5 },
  ],
  "dog": [
    { file: "/se/lib/dog/mix1.mp3", title: "dog ミックス 1（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/dog/mix2.mp3", title: "dog ミックス 2（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/dog/mix3.mp3", title: "dog ミックス 3（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/dog/mix4.mp3", title: "dog ミックス 4（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/dog/mix5.mp3", title: "dog ミックス 5（8 素材・6.5s）", seconds: 6.5 },
  ],
  "pig": [
    { file: "/se/lib/pig/mix1.mp3", title: "pig ミックス 1（8 素材・6.3s）", seconds: 6.3 },
    { file: "/se/lib/pig/mix2.mp3", title: "pig ミックス 2（8 素材・4.9s）", seconds: 4.94 },
    { file: "/se/lib/pig/mix3.mp3", title: "pig ミックス 3（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/pig/mix4.mp3", title: "pig ミックス 4（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/pig/mix5.mp3", title: "pig ミックス 5（8 素材・6.5s）", seconds: 6.5 },
  ],
  "elephant": [
    { file: "/se/lib/elephant/mix1.mp3", title: "elephant ミックス 1（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/elephant/mix2.mp3", title: "elephant ミックス 2（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/elephant/mix3.mp3", title: "elephant ミックス 3（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/elephant/mix4.mp3", title: "elephant ミックス 4（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/elephant/mix5.mp3", title: "elephant ミックス 5（8 素材・6.5s）", seconds: 6.5 },
  ],
  "wolf": [
    { file: "/se/lib/wolf/mix1.mp3", title: "wolf ミックス 1（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/wolf/mix2.mp3", title: "wolf ミックス 2（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/wolf/mix3.mp3", title: "wolf ミックス 3（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/wolf/mix4.mp3", title: "wolf ミックス 4（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/wolf/mix5.mp3", title: "wolf ミックス 5（8 素材・6.5s）", seconds: 6.5 },
  ],
  "lion": [
    { file: "/se/lib/lion/mix1.mp3", title: "lion ミックス 1（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/lion/mix2.mp3", title: "lion ミックス 2（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/lion/mix3.mp3", title: "lion ミックス 3（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/lion/mix4.mp3", title: "lion ミックス 4（11 素材・9.3s）", seconds: 9.28 },
    { file: "/se/lib/lion/mix5.mp3", title: "lion ミックス 5（11 素材・8.2s）", seconds: 8.24 },
  ],
  "bird": [
    { file: "/se/lib/bird/mix1.mp3", title: "bird ミックス 1（4 素材・3.5s）", seconds: 3.5 },
    { file: "/se/lib/bird/mix2.mp3", title: "bird ミックス 2（4 素材・3.2s）", seconds: 3.18 },
    { file: "/se/lib/bird/mix3.mp3", title: "bird ミックス 3（4 素材・3.5s）", seconds: 3.5 },
    { file: "/se/lib/bird/mix4.mp3", title: "bird ミックス 4（4 素材・3.2s）", seconds: 3.18 },
    { file: "/se/lib/bird/mix5.mp3", title: "bird ミックス 5（4 素材・3.5s）", seconds: 3.5 },
  ],
  "horse": [
    { file: "/se/lib/horse/mix1.mp3", title: "horse ミックス 1（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/horse/mix2.mp3", title: "horse ミックス 2（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/horse/mix3.mp3", title: "horse ミックス 3（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/horse/mix4.mp3", title: "horse ミックス 4（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/horse/mix5.mp3", title: "horse ミックス 5（8 素材・6.5s）", seconds: 6.5 },
  ],
  "cow": [
    { file: "/se/lib/cow/mix1.mp3", title: "cow ミックス 1（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/cow/mix2.mp3", title: "cow ミックス 2（8 素材・6.4s）", seconds: 6.41 },
    { file: "/se/lib/cow/mix3.mp3", title: "cow ミックス 3（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/cow/mix4.mp3", title: "cow ミックス 4（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/cow/mix5.mp3", title: "cow ミックス 5（8 素材・6.5s）", seconds: 6.5 },
  ],
  "monkey": [
    { file: "/se/lib/monkey/mix1.mp3", title: "monkey ミックス 1（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/monkey/mix2.mp3", title: "monkey ミックス 2（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/monkey/mix3.mp3", title: "monkey ミックス 3（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/monkey/mix4.mp3", title: "monkey ミックス 4（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/monkey/mix5.mp3", title: "monkey ミックス 5（8 素材・6.5s）", seconds: 6.5 },
  ],
  "bear": [
    { file: "/se/lib/bear/mix1.mp3", title: "bear ミックス 1（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/bear/mix2.mp3", title: "bear ミックス 2（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/bear/mix3.mp3", title: "bear ミックス 3（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/bear/mix4.mp3", title: "bear ミックス 4（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/bear/mix5.mp3", title: "bear ミックス 5（8 素材・6.5s）", seconds: 6.5 },
  ],
  "cute": [
    { file: "/se/lib/cute/mix1.mp3", title: "cute ミックス 1（4 素材・3.5s）", seconds: 3.5 },
    { file: "/se/lib/cute/mix2.mp3", title: "cute ミックス 2（4 素材・3.5s）", seconds: 3.5 },
    { file: "/se/lib/cute/mix3.mp3", title: "cute ミックス 3（4 素材・3.5s）", seconds: 3.5 },
    { file: "/se/lib/cute/mix4.mp3", title: "cute ミックス 4（4 素材・3.3s）", seconds: 3.27 },
    { file: "/se/lib/cute/mix5.mp3", title: "cute ミックス 5（4 素材・3.2s）", seconds: 3.2 },
  ],
  "drink": [
    { file: "/se/lib/drink/mix1.mp3", title: "drink ミックス 1（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/drink/mix2.mp3", title: "drink ミックス 2（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/drink/mix3.mp3", title: "drink ミックス 3（8 素材・5.2s）", seconds: 5.24 },
    { file: "/se/lib/drink/mix4.mp3", title: "drink ミックス 4（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/drink/mix5.mp3", title: "drink ミックス 5（8 素材・6.5s）", seconds: 6.5 },
  ],
  "food": [
    { file: "/se/lib/food/mix1.mp3", title: "food ミックス 1（4 素材・3.5s）", seconds: 3.5 },
    { file: "/se/lib/food/mix2.mp3", title: "food ミックス 2（4 素材・3.5s）", seconds: 3.5 },
    { file: "/se/lib/food/mix3.mp3", title: "food ミックス 3（4 素材・3.3s）", seconds: 3.3 },
    { file: "/se/lib/food/mix4.mp3", title: "food ミックス 4（4 素材・3.5s）", seconds: 3.5 },
    { file: "/se/lib/food/mix5.mp3", title: "food ミックス 5（4 素材・3.5s）", seconds: 3.5 },
  ],
  "party": [
    { file: "/se/lib/party/mix1.mp3", title: "party ミックス 1（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/party/mix2.mp3", title: "party ミックス 2（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/party/mix3.mp3", title: "party ミックス 3（11 素材・8.5s）", seconds: 8.47 },
    { file: "/se/lib/party/mix4.mp3", title: "party ミックス 4（11 素材・9.3s）", seconds: 9.3 },
    { file: "/se/lib/party/mix5.mp3", title: "party ミックス 5（11 素材・9.5s）", seconds: 9.5 },
  ],
  "bell": [
    { file: "/se/lib/bell/mix1.mp3", title: "bell ミックス 1（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/bell/mix2.mp3", title: "bell ミックス 2（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/bell/mix3.mp3", title: "bell ミックス 3（8 素材・6.1s）", seconds: 6.07 },
    { file: "/se/lib/bell/mix4.mp3", title: "bell ミックス 4（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/bell/mix5.mp3", title: "bell ミックス 5（8 素材・6.5s）", seconds: 6.5 },
  ],
  "christmas": [
    { file: "/se/lib/christmas/mix1.mp3", title: "christmas ミックス 1（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/christmas/mix2.mp3", title: "christmas ミックス 2（8 素材・5.3s）", seconds: 5.34 },
    { file: "/se/lib/christmas/mix3.mp3", title: "christmas ミックス 3（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/christmas/mix4.mp3", title: "christmas ミックス 4（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/christmas/mix5.mp3", title: "christmas ミックス 5（8 素材・6.5s）", seconds: 6.5 },
  ],
  "halloween": [
    { file: "/se/lib/halloween/mix1.mp3", title: "halloween ミックス 1（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/halloween/mix2.mp3", title: "halloween ミックス 2（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/halloween/mix3.mp3", title: "halloween ミックス 3（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/halloween/mix4.mp3", title: "halloween ミックス 4（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/halloween/mix5.mp3", title: "halloween ミックス 5（8 素材・6.5s）", seconds: 6.5 },
  ],
  "sea": [
    { file: "/se/lib/sea/mix1.mp3", title: "sea ミックス 1（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/sea/mix2.mp3", title: "sea ミックス 2（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/sea/mix3.mp3", title: "sea ミックス 3（8 素材・6.4s）", seconds: 6.43 },
    { file: "/se/lib/sea/mix4.mp3", title: "sea ミックス 4（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/sea/mix5.mp3", title: "sea ミックス 5（8 素材・6.3s）", seconds: 6.27 },
  ],
  "rocket": [
    { file: "/se/lib/rocket/mix1.mp3", title: "rocket ミックス 1（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/rocket/mix2.mp3", title: "rocket ミックス 2（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/rocket/mix3.mp3", title: "rocket ミックス 3（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/rocket/mix4.mp3", title: "rocket ミックス 4（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/rocket/mix5.mp3", title: "rocket ミックス 5（11 素材・9.5s）", seconds: 9.5 },
  ],
  "explosion": [
    { file: "/se/lib/explosion/mix1.mp3", title: "explosion ミックス 1（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/explosion/mix2.mp3", title: "explosion ミックス 2（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/explosion/mix3.mp3", title: "explosion ミックス 3（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/explosion/mix4.mp3", title: "explosion ミックス 4（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/explosion/mix5.mp3", title: "explosion ミックス 5（11 素材・9.5s）", seconds: 9.5 },
  ],
  "casino": [
    { file: "/se/lib/casino/mix1.mp3", title: "casino ミックス 1（12 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/casino/mix2.mp3", title: "casino ミックス 2（12 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/casino/mix3.mp3", title: "casino ミックス 3（12 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/casino/mix4.mp3", title: "casino ミックス 4（12 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/casino/mix5.mp3", title: "casino ミックス 5（12 素材・9.5s）", seconds: 9.5 },
  ],
  "music": [
    { file: "/se/lib/music/mix1.mp3", title: "music ミックス 1（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/music/mix2.mp3", title: "music ミックス 2（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/music/mix3.mp3", title: "music ミックス 3（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/music/mix4.mp3", title: "music ミックス 4（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/music/mix5.mp3", title: "music ミックス 5（8 素材・6.2s）", seconds: 6.25 },
  ],
  "battle": [
    { file: "/se/lib/battle/mix1.mp3", title: "battle ミックス 1（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/battle/mix2.mp3", title: "battle ミックス 2（11 素材・8.9s）", seconds: 8.91 },
    { file: "/se/lib/battle/mix3.mp3", title: "battle ミックス 3（11 素材・9.3s）", seconds: 9.31 },
    { file: "/se/lib/battle/mix4.mp3", title: "battle ミックス 4（11 素材・8.8s）", seconds: 8.77 },
    { file: "/se/lib/battle/mix5.mp3", title: "battle ミックス 5（11 素材・8.9s）", seconds: 8.94 },
  ],
  "vehicle": [
    { file: "/se/lib/vehicle/mix1.mp3", title: "vehicle ミックス 1（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/vehicle/mix2.mp3", title: "vehicle ミックス 2（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/vehicle/mix3.mp3", title: "vehicle ミックス 3（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/vehicle/mix4.mp3", title: "vehicle ミックス 4（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/vehicle/mix5.mp3", title: "vehicle ミックス 5（8 素材・6.5s）", seconds: 6.5 },
  ],
  "flower": [
    { file: "/se/lib/flower/mix1.mp3", title: "flower ミックス 1（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/flower/mix2.mp3", title: "flower ミックス 2（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/flower/mix3.mp3", title: "flower ミックス 3（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/flower/mix4.mp3", title: "flower ミックス 4（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/flower/mix5.mp3", title: "flower ミックス 5（8 素材・6.5s）", seconds: 6.5 },
  ],
  "pop": [
    { file: "/se/lib/pop/mix1.mp3", title: "pop ミックス 1（4 素材・3.5s）", seconds: 3.5 },
    { file: "/se/lib/pop/mix2.mp3", title: "pop ミックス 2（4 素材・3.4s）", seconds: 3.38 },
    { file: "/se/lib/pop/mix3.mp3", title: "pop ミックス 3（4 素材・3.5s）", seconds: 3.5 },
    { file: "/se/lib/pop/mix4.mp3", title: "pop ミックス 4（4 素材・3.2s）", seconds: 3.19 },
    { file: "/se/lib/pop/mix5.mp3", title: "pop ミックス 5（4 素材・3.2s）", seconds: 3.25 },
  ],
  "trophy": [
    { file: "/se/lib/trophy/mix1.mp3", title: "trophy ミックス 1（14 素材・10.6s）", seconds: 10.62 },
    { file: "/se/lib/trophy/mix2.mp3", title: "trophy ミックス 2（14 素材・12.0s）", seconds: 12.0 },
    { file: "/se/lib/trophy/mix3.mp3", title: "trophy ミックス 3（14 素材・12.0s）", seconds: 12.0 },
    { file: "/se/lib/trophy/mix4.mp3", title: "trophy ミックス 4（14 素材・12.0s）", seconds: 12.0 },
    { file: "/se/lib/trophy/mix5.mp3", title: "trophy ミックス 5（14 素材・12.0s）", seconds: 12.0 },
  ],
  "epic": [
    { file: "/se/lib/epic/mix1.mp3", title: "epic ミックス 1（14 素材・15.0s）", seconds: 15.0 },
    { file: "/se/lib/epic/mix2.mp3", title: "epic ミックス 2（14 素材・14.3s）", seconds: 14.35 },
    { file: "/se/lib/epic/mix3.mp3", title: "epic ミックス 3（14 素材・13.7s）", seconds: 13.68 },
    { file: "/se/lib/epic/mix4.mp3", title: "epic ミックス 4（14 素材・15.0s）", seconds: 15.0 },
    { file: "/se/lib/epic/mix5.mp3", title: "epic ミックス 5（14 素材・13.9s）", seconds: 13.87 },
  ],
  "notify": [
    { file: "/se/lib/notify/mix1.mp3", title: "notify ミックス 1（4 素材・3.5s）", seconds: 3.5 },
    { file: "/se/lib/notify/mix2.mp3", title: "notify ミックス 2（4 素材・2.3s）", seconds: 2.28 },
    { file: "/se/lib/notify/mix3.mp3", title: "notify ミックス 3（4 素材・3.4s）", seconds: 3.39 },
    { file: "/se/lib/notify/mix4.mp3", title: "notify ミックス 4（4 素材・3.5s）", seconds: 3.5 },
    { file: "/se/lib/notify/mix5.mp3", title: "notify ミックス 5（4 素材・3.5s）", seconds: 3.5 },
  ],
  "wow": [
    { file: "/se/lib/wow/mix1.mp3", title: "wow ミックス 1（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/wow/mix2.mp3", title: "wow ミックス 2（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/wow/mix3.mp3", title: "wow ミックス 3（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/wow/mix4.mp3", title: "wow ミックス 4（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/wow/mix5.mp3", title: "wow ミックス 5（11 素材・9.5s）", seconds: 9.5 },
  ],
  "dice": [
    { file: "/se/lib/dice/mix1.mp3", title: "dice ミックス 1（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/dice/mix2.mp3", title: "dice ミックス 2（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/dice/mix3.mp3", title: "dice ミックス 3（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/dice/mix4.mp3", title: "dice ミックス 4（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/dice/mix5.mp3", title: "dice ミックス 5（8 素材・6.5s）", seconds: 6.5 },
  ],
  "kids": [
    { file: "/se/lib/kids/mix1.mp3", title: "kids ミックス 1（4 素材・3.5s）", seconds: 3.5 },
    { file: "/se/lib/kids/mix2.mp3", title: "kids ミックス 2（4 素材・3.5s）", seconds: 3.5 },
    { file: "/se/lib/kids/mix3.mp3", title: "kids ミックス 3（4 素材・3.5s）", seconds: 3.5 },
    { file: "/se/lib/kids/mix4.mp3", title: "kids ミックス 4（4 素材・3.5s）", seconds: 3.5 },
    { file: "/se/lib/kids/mix5.mp3", title: "kids ミックス 5（4 素材・3.5s）", seconds: 3.5 },
  ],
  "thunder": [
    { file: "/se/lib/thunder/mix1.mp3", title: "thunder ミックス 1（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/thunder/mix2.mp3", title: "thunder ミックス 2（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/thunder/mix3.mp3", title: "thunder ミックス 3（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/thunder/mix4.mp3", title: "thunder ミックス 4（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/thunder/mix5.mp3", title: "thunder ミックス 5（11 素材・9.5s）", seconds: 9.5 },
  ],
  "fire": [
    { file: "/se/lib/fire/mix1.mp3", title: "fire ミックス 1（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/fire/mix2.mp3", title: "fire ミックス 2（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/fire/mix3.mp3", title: "fire ミックス 3（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/fire/mix4.mp3", title: "fire ミックス 4（11 素材・9.5s）", seconds: 9.5 },
    { file: "/se/lib/fire/mix5.mp3", title: "fire ミックス 5（11 素材・9.5s）", seconds: 9.5 },
  ],
  "laser": [
    { file: "/se/lib/laser/mix1.mp3", title: "laser ミックス 1（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/laser/mix2.mp3", title: "laser ミックス 2（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/laser/mix3.mp3", title: "laser ミックス 3（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/laser/mix4.mp3", title: "laser ミックス 4（8 素材・6.5s）", seconds: 6.5 },
    { file: "/se/lib/laser/mix5.mp3", title: "laser ミックス 5（8 素材・6.5s）", seconds: 6.5 },
  ],
  "whoosh": [
    { file: "/se/lib/whoosh/mix1.mp3", title: "whoosh ミックス 1（4 素材・3.5s）", seconds: 3.5 },
    { file: "/se/lib/whoosh/mix2.mp3", title: "whoosh ミックス 2（4 素材・3.5s）", seconds: 3.46 },
    { file: "/se/lib/whoosh/mix3.mp3", title: "whoosh ミックス 3（4 素材・3.5s）", seconds: 3.5 },
    { file: "/se/lib/whoosh/mix4.mp3", title: "whoosh ミックス 4（4 素材・3.5s）", seconds: 3.5 },
    { file: "/se/lib/whoosh/mix5.mp3", title: "whoosh ミックス 5（4 素材・3.5s）", seconds: 3.5 },
  ],
  "bulk-COOL": [
    { file: "/se/lib/bulk-COOL/mix1.mp3", title: "bulk-COOL ミックス 1（8 素材・6.0s）", seconds: 6.0 },
    { file: "/se/lib/bulk-COOL/mix2.mp3", title: "bulk-COOL ミックス 2（8 素材・6.0s）", seconds: 6.0 },
    { file: "/se/lib/bulk-COOL/mix3.mp3", title: "bulk-COOL ミックス 3（8 素材・6.0s）", seconds: 6.0 },
    { file: "/se/lib/bulk-COOL/mix4.mp3", title: "bulk-COOL ミックス 4（8 素材・6.0s）", seconds: 6.0 },
    { file: "/se/lib/bulk-COOL/mix5.mp3", title: "bulk-COOL ミックス 5（8 素材・5.9s）", seconds: 5.93 },
  ],
  "bulk-GREAT": [
    { file: "/se/lib/bulk-GREAT/mix1.mp3", title: "bulk-GREAT ミックス 1（11 素材・9.0s）", seconds: 9.0 },
    { file: "/se/lib/bulk-GREAT/mix2.mp3", title: "bulk-GREAT ミックス 2（11 素材・9.0s）", seconds: 9.0 },
    { file: "/se/lib/bulk-GREAT/mix3.mp3", title: "bulk-GREAT ミックス 3（11 素材・9.0s）", seconds: 9.0 },
    { file: "/se/lib/bulk-GREAT/mix4.mp3", title: "bulk-GREAT ミックス 4（11 素材・9.0s）", seconds: 9.0 },
    { file: "/se/lib/bulk-GREAT/mix5.mp3", title: "bulk-GREAT ミックス 5（11 素材・9.0s）", seconds: 9.0 },
  ],
  "bulk-FANTASTIC": [
    { file: "/se/lib/bulk-FANTASTIC/mix1.mp3", title: "bulk-FANTASTIC ミックス 1（15 素材・12.0s）", seconds: 12.0 },
    { file: "/se/lib/bulk-FANTASTIC/mix2.mp3", title: "bulk-FANTASTIC ミックス 2（15 素材・12.0s）", seconds: 12.0 },
    { file: "/se/lib/bulk-FANTASTIC/mix3.mp3", title: "bulk-FANTASTIC ミックス 3（15 素材・12.0s）", seconds: 12.0 },
    { file: "/se/lib/bulk-FANTASTIC/mix4.mp3", title: "bulk-FANTASTIC ミックス 4（15 素材・12.0s）", seconds: 12.0 },
    { file: "/se/lib/bulk-FANTASTIC/mix5.mp3", title: "bulk-FANTASTIC ミックス 5（15 素材・12.0s）", seconds: 12.0 },
  ],
  "bulk-MIRACLE": [
    { file: "/se/lib/bulk-MIRACLE/mix1.mp3", title: "bulk-MIRACLE ミックス 1（15 素材・15.0s）", seconds: 15.0 },
    { file: "/se/lib/bulk-MIRACLE/mix2.mp3", title: "bulk-MIRACLE ミックス 2（15 素材・15.0s）", seconds: 15.0 },
    { file: "/se/lib/bulk-MIRACLE/mix3.mp3", title: "bulk-MIRACLE ミックス 3（15 素材・15.0s）", seconds: 15.0 },
    { file: "/se/lib/bulk-MIRACLE/mix4.mp3", title: "bulk-MIRACLE ミックス 4（15 素材・12.0s）", seconds: 11.99 },
    { file: "/se/lib/bulk-MIRACLE/mix5.mp3", title: "bulk-MIRACLE ミックス 5（15 素材・15.0s）", seconds: 15.0 },
  ],
  "tier-T0": [
    { file: "/se/lib/tier-T0/mix1.mp3", title: "tier-T0 ミックス 1（4 素材・3.0s）", seconds: 3.0 },
    { file: "/se/lib/tier-T0/mix2.mp3", title: "tier-T0 ミックス 2（4 素材・3.0s）", seconds: 3.0 },
    { file: "/se/lib/tier-T0/mix3.mp3", title: "tier-T0 ミックス 3（4 素材・3.0s）", seconds: 3.0 },
    { file: "/se/lib/tier-T0/mix4.mp3", title: "tier-T0 ミックス 4（4 素材・3.0s）", seconds: 3.0 },
    { file: "/se/lib/tier-T0/mix5.mp3", title: "tier-T0 ミックス 5（4 素材・3.0s）", seconds: 3.0 },
  ],
  "tier-T1": [
    { file: "/se/lib/tier-T1/mix1.mp3", title: "tier-T1 ミックス 1（4 素材・4.0s）", seconds: 4.0 },
    { file: "/se/lib/tier-T1/mix2.mp3", title: "tier-T1 ミックス 2（4 素材・4.0s）", seconds: 4.0 },
    { file: "/se/lib/tier-T1/mix3.mp3", title: "tier-T1 ミックス 3（4 素材・4.0s）", seconds: 4.0 },
    { file: "/se/lib/tier-T1/mix4.mp3", title: "tier-T1 ミックス 4（4 素材・4.0s）", seconds: 4.0 },
    { file: "/se/lib/tier-T1/mix5.mp3", title: "tier-T1 ミックス 5（4 素材・4.0s）", seconds: 4.0 },
  ],
  "tier-T2": [
    { file: "/se/lib/tier-T2/mix1.mp3", title: "tier-T2 ミックス 1（8 素材・5.5s）", seconds: 5.52 },
    { file: "/se/lib/tier-T2/mix2.mp3", title: "tier-T2 ミックス 2（8 素材・5.6s）", seconds: 5.65 },
    { file: "/se/lib/tier-T2/mix3.mp3", title: "tier-T2 ミックス 3（8 素材・6.0s）", seconds: 6.0 },
    { file: "/se/lib/tier-T2/mix4.mp3", title: "tier-T2 ミックス 4（8 素材・5.8s）", seconds: 5.85 },
    { file: "/se/lib/tier-T2/mix5.mp3", title: "tier-T2 ミックス 5（8 素材・5.8s）", seconds: 5.76 },
  ],
  "tier-T3": [
    { file: "/se/lib/tier-T3/mix1.mp3", title: "tier-T3 ミックス 1（11 素材・9.0s）", seconds: 9.0 },
    { file: "/se/lib/tier-T3/mix2.mp3", title: "tier-T3 ミックス 2（11 素材・9.0s）", seconds: 9.0 },
    { file: "/se/lib/tier-T3/mix3.mp3", title: "tier-T3 ミックス 3（11 素材・9.0s）", seconds: 9.0 },
    { file: "/se/lib/tier-T3/mix4.mp3", title: "tier-T3 ミックス 4（11 素材・9.0s）", seconds: 9.0 },
    { file: "/se/lib/tier-T3/mix5.mp3", title: "tier-T3 ミックス 5（11 素材・9.0s）", seconds: 9.0 },
  ],
  "tier-T4": [
    { file: "/se/lib/tier-T4/mix1.mp3", title: "tier-T4 ミックス 1（15 素材・13.5s）", seconds: 13.48 },
    { file: "/se/lib/tier-T4/mix2.mp3", title: "tier-T4 ミックス 2（15 素材・14.8s）", seconds: 14.85 },
    { file: "/se/lib/tier-T4/mix3.mp3", title: "tier-T4 ミックス 3（15 素材・12.0s）", seconds: 12.01 },
    { file: "/se/lib/tier-T4/mix4.mp3", title: "tier-T4 ミックス 4（15 素材・15.0s）", seconds: 15.0 },
    { file: "/se/lib/tier-T4/mix5.mp3", title: "tier-T4 ミックス 5（15 素材・13.5s）", seconds: 13.52 },
  ],
  "hit": [
    { file: "/se/lib/hit/mix1.mp3", title: "hit ミックス 1（12 素材・10.0s）", seconds: 10.0 },
    { file: "/se/lib/hit/mix2.mp3", title: "hit ミックス 2（12 素材・10.0s）", seconds: 10.0 },
    { file: "/se/lib/hit/mix3.mp3", title: "hit ミックス 3（12 素材・10.0s）", seconds: 10.0 },
    { file: "/se/lib/hit/mix4.mp3", title: "hit ミックス 4（12 素材・10.0s）", seconds: 10.0 },
    { file: "/se/lib/hit/mix5.mp3", title: "hit ミックス 5（12 素材・10.0s）", seconds: 10.0 },
  ],
};

export const AUTO_LIBRARY_FILE_COUNT = 285;
